.github/workflows/CI.yml, .pre-commit-config.yaml, pyproject.toml
Add a few things to help make Black a more useful utility.
- `pyproject.toml`: What you can config with Black is controlled through `pyproject.toml`, so avoid Black-ing things that don't need it
- `.pre-commit-config.yaml`: If you run `pre-commit install` then Black will be run automatically every time you try to commit
- `black --check --diff --verbose .` gives much more helpful output to the CI logs
Squash and merge suggested commit message:
```
* Add pyproject.toml for Black config
* Add .pre-commit-config.yaml for Black pre-commit hook
* Use --check --diff --verbose in CI for more helpful log output
```
=> chore: Add Black helper utilities

example.py, src/cabinetry/config.py, src/cabinetry/contrib/histogram_drawing.py, src/cabinetry/histogram_wrapper.py, src/cabinetry/template_builder.py, src/cabinetry/template_postprocessor.py, src/cabinetry/visualize.py
Switching from print statements to using the python `logging` module allows users to customize their output  and more easily parse it.
=> feat: using logging instead of prints

.github/workflows/CI.yml, .gitignore, README.md, src/cabinetry/contrib/histogram_creation.py, src/cabinetry/contrib/histogram_drawing.py, src/cabinetry/histogram_wrapper.py, src/cabinetry/template_builder.py, src/cabinetry/template_postprocessor.py, src/cabinetry/visualize.py, util/create_histograms.py
This adds reading and propagating of statistical uncertainties, changes the way histograms are passed around internally to a dict, and propagates the new information to the plotting code as well. It also adds examples and infrastructure for sanity checks for the histograms. Lastly, a small readme update with instructions for running a simple example.
```
* statistical uncertainty extraction and propagation for histograms
* data/MC drawing improvements
* sanity checks for histograms
* functionality to load original/post-processed histogram
```
=> feat: statistical uncertainties for histograms

.github/workflows/CI.yml
#8 introduced an `iminuit` dependency through `pyhf`, which needs to be manually installed for the CI.
=> ci: adding iminuit dependency

README.md, setup.py, src/cabinetry/__init__.py
Adding the missing dependencies introduced via the workspace building and fit features, and setting minimum `pyhf` version required.
Preparing for next tag `v0.0.2`.
=> build: updating dependencies

.github/workflows/CI.yml
The `flake8` check pointed to `cabinetry` instead of `src/cabinetry`, fixed with this.
=> ci: fixing flake8 path

src/cabinetry/fit.py
With `flake8` working again properly via #13, this fixes the two issues it raised.
=> style: fixing issues raised by flake8

.github/workflows/CI.yml, .gitignore, example.py, src/cabinetry/fit.py, src/cabinetry/histo.py, src/cabinetry/visualize.py, tests/contrib/test_histogram_creation.py, tests/contrib/test_histogram_drawing.py, tests/test_config.py, tests/test_fit.py, tests/test_histo.py, tests/test_template_builder.py, tests/test_template_postprocessor.py, tests/test_visualize.py, tests/test_workspace.py
Adding the first tests to be run with `pytest` to test framework functionality. All modules are tested separately. Also fixing a typo for postfit histogram naming and returning MLE fit results for easier access. CI expanded to test python 3.6, 3.7, 3.8.
=> test: adding first tests

example.py, tests/test_fit.py
`pytest` reports a warning produced likely due to different `numpy` versions used by `cabinetry` dependencies, this ignores the warning. See also https://github.com/scikit-hep/pyhf/issues/871. Small formatting fix in example script.
=> test: ignoring numpy warning

example.py, src/cabinetry/config.py, src/cabinetry/contrib/histogram_drawing.py, src/cabinetry/histo.py, src/cabinetry/template_builder.py, src/cabinetry/template_postprocessor.py, src/cabinetry/visualize.py, src/cabinetry/workspace.py, tests/test_fit.py, tests/test_histo.py, tests/test_template_builder.py, util/create_histograms.py
Using `pathlib` for file path handling. Adding workspace loading and a more convenient histogram loading function. Updating various docstrings and fixing some flake8 warnings.
=> refactor: file path handling

README.md, example.py
Adding simple example of `cabinetry` use to readme and removing unnecessary line from example.
=> docs: hello world example

src/cabinetry/contrib/histogram_creation.py, src/cabinetry/histo.py, src/cabinetry/template_builder.py, tests/test_histo.py, tests/test_template_builder.py
Adding tests for histogram file handling, and adding small improvements to existing tests. Also refactoring the internal handling of histograms: instead of using lists, numpy.ndarrays are used for yields/sumw2/bins.
=> test: file handling

README.md, config_example.yml, example.py, src/cabinetry/__init__.py, src/cabinetry/configuration.py, src/cabinetry/histo.py, src/cabinetry/template_builder.py, src/cabinetry/template_postprocessor.py, src/cabinetry/workspace.py, tests/test_config.py, tests/test_template_builder.py, util/create_histograms.py
- renaming config module to configuration
- additional distribution created in toy ntuple script to test template-based variations
- fixes in logic for histogram creation and modifier creation in workspace
- removing nominal-only histogram creation option
- support for two-point systematics (shape and normalization effect from comparing two templates)
=> feat: two-point systematics

.pre-commit-config.yaml
adding a check for large (>100 KB) files and trailing whitespaces
=> chore: more pre-commit checks

.gitignore, README.md, docs/api.rst, docs/conf.py, docs/index.rst, docs/license.rst
Adding a basic structure for documentation with `Sphinx`. This should be expanded further and automatically built and deployed somewhere in the future.
=> docs: basic Sphinx setup

.github/workflows/CI.yml, setup.py
Use the `extras_require` ability in `setup.py` to establish "extras" environments that can define the specific dependencies for all stages of the development process. Additionally, add a "complete" extra to be able to install everything a core developer might want.
Suggested squash and merged commit log entry:
```
* Add use of extras_require to setup.py
* Add 'contrib', 'test', 'develop', and 'complete' extras
* Use 'test' extra in CI to install all necessary dependencies
* Update to use GitHub Action setup-python v2
```
=> feat: Add setup 'extras' to provide install options for dependencies

src/cabinetry/workspace.py, tests/contrib/test_histogram_creation.py, tests/test_histo.py, tests/test_template_builder.py, tests/test_template_postprocessor.py, tests/test_workspace.py
Adding more tests for histograms / workspace functionality, plus fixes to the histogram components in the tests. Also adding tests for uproot backend in `contrib`, and switching from use of `tmpdir` to `tmp_path` everywhere.
=> test: additional tests

codecov.yml
Adding a settings file to configure https://codecov.io/. The threshold of 1% will cause the codecov check to fail only when coverage decreases by more than 1%. This is useful for cases like #37. The threshold should be reduced as the codebase expands.
=> ci: codecov settings

src/cabinetry/fit.py, tests/test_fit.py
enable the return of twice the negative log likelihood at the best-fit point in `cabinetry.fit.fit()`
=> feat: nll at best-fit point

src/cabinetry/histo.py, src/cabinetry/template_builder.py, src/cabinetry/template_postprocessor.py, src/cabinetry/visualize.py, src/cabinetry/workspace.py, tests/contrib/test_histogram_drawing.py, tests/test_configuration.py, tests/test_histo.py, tests/test_template_builder.py, tests/test_template_postprocessor.py, tests/test_visualize.py, tests/test_workspace.py
Creating a histogram class to simplify the internal handling. This should later on also help when exchanging histograms by differentiable alternatives.
=> refactor: histogram class

README.md, config_example.yml, src/cabinetry/configuration.py, src/cabinetry/histo.py, src/cabinetry/template_builder.py, src/cabinetry/template_postprocessor.py, src/cabinetry/visualize.py, src/cabinetry/workspace.py, tests/test_configuration.py, tests/test_histo.py, tests/test_template_builder.py, tests/test_template_postprocessor.py, tests/test_visualize.py, tests/test_workspace.py
Templates are categorized by phase space region, sample, and systematic variation. Before this PR, the internal structure was accessing them as (sample , region, systematic). This changes the coordinates to use (region, sample, systematic) instead.
Motivation for this change:
- A phase space region does not logically depend on either samples or systematics. While neither the list of samples nor systematics generally strongly depend on the phase space region, they can.
- Systematic variations affect samples, and the list of variations is sample-dependent. It feels intuitively better to think of samples as a higher up category than systematics.
=> refactor: order of coordinates for templates

docs/index.rst, setup.py, src/cabinetry/contrib/histogram_creation.py, tests/contrib/test_histogram_creation.py
Instead of using `scipy` to histogram the output from `uproot` in `cabinetry.contrib`, switch to using [boost_histogram](https://github.com/scikit-hep/boost-histogram).
It might make sense to also use `boost_histogram` in `cabinetry.histo.Histogram`, which would make it a core dependency. This is a separate consideration for the future.
Also removing `iminuit` from install extras, since it is already a core dependency.
=> refactor: boost_histogram for histogramming

setup.py, src/cabinetry/contrib/histogram_creation.py
Switching to `uproot4` in `cabinetry.contrib` for ntuple reading. This requires also the addition of `awkward1` to the setup extras. The package names need to be updated when the transition `uproot4` -> `uproot` and `awkward1` -> `awkward` happens.
`uproot` is still needed for the ntuple creation code in `util/`, but `numexpr` is no longer needed as the cut functionality is provided by `uproot4`.
=> refactor:  uproot4 in contrib

.github/workflows/CI.yml, src/cabinetry/contrib/histogram_drawing.py, tests/test_integration.py, util/create_ntuples.py
Adding an integration test based on the example in `example.py`. This integration test is not included in the determination of coverage.
Renaming and slightly refactoring the ntuple creation script, and updating the matplotlib backend to properly clean up the figure between tests.
=> test: integration test

setup.py, src/cabinetry/contrib/histogram_creation.py, src/cabinetry/contrib/histogram_drawing.py, src/cabinetry/histo.py, src/cabinetry/template_builder.py, src/cabinetry/template_postprocessor.py, src/cabinetry/visualize.py, src/cabinetry/workspace.py, tests/contrib/test_histogram_creation.py, tests/contrib/test_histogram_drawing.py, tests/test_histo.py, tests/test_template_builder.py, tests/test_template_postprocessor.py, tests/test_visualize.py, tests/test_workspace.py
Inherit `cabinetry.histo.Histogram` from `boost_histogram.Histogram`. Switching to [boost-histogram](https://github.com/scikit-hep/boost-histogram) should make the histogram API more familiar to users who already know it from elsewhere, and will be useful to make use of [hist](https://github.com/scikit-hep/hist) in the future.
Renaming `sumw2` to `stdev`, the old name was wrong (the sum of weights squared is the variance).
=> refactor: switch to boost-histogram

example.py, src/cabinetry/configuration.py, src/cabinetry/contrib/histogram_drawing.py, src/cabinetry/fit.py, src/cabinetry/histo.py, src/cabinetry/template_builder.py, src/cabinetry/template_postprocessor.py, src/cabinetry/visualize.py, src/cabinetry/workspace.py
Switching to f-strings for logging, even though [logging internally uses %-format strings](https://docs.python.org/3/howto/logging-cookbook.html#formatting-styles). The f-string format is more readable.
=> refactor: f-strings for logging

.github/workflows/CI.yml, src/cabinetry/configuration.py, src/cabinetry/fit.py, src/cabinetry/histo.py, src/cabinetry/template_builder.py, src/cabinetry/template_postprocessor.py, src/cabinetry/visualize.py, src/cabinetry/workspace.py
Fixing warnings from `flake8` due to the switch to f-strings in #58. Also updating the CI such that any warnings from `flake8` will now fail it.
=> style: flake8 string fixes

config_example.yml, src/cabinetry/configuration.py, src/cabinetry/histo.py, src/cabinetry/template_builder.py, src/cabinetry/template_postprocessor.py, src/cabinetry/workspace.py, tests/test_configuration.py, tests/test_template_builder.py, tests/test_workspace.py
Switching the config layout from being a flat list of options per systematic to a new version where each template is specified via its own dict. This allows to re-use the same names for the same types of options.
Example:
A sample has an option `Path` pointing to where the relevant input file is located. A systematic with two templates `Up` and `Down` has the following structure to point to the two paths:
YAML:
```yaml
Up:
Path: ...
Down:
Path: ...
```
JSON:
```json
{
"Down": {
"Path": "..."
}, 
"Up": {
"Path": "..."
}
}
```
This approach is a small step towards #51, as additional templates can be specified via a list of dicts in the same manner.
Additional things done in this PR:
- Renaming OverallSys to Normalization.
- Removing the color options from the config, as they currently serve …
=> refactor: specification of systematics templates

config_example.yml, example.py, src/cabinetry/configuration.py, src/cabinetry/workspace.py, tests/test_configuration.py, tests/test_integration.py, tests/test_workspace.py
Propagating norm factor settings from the config to the `pyhf` workspace. The available settings are:
- nominal value ("Nominal")
- parameter boundaries ("Bounds"), as a list `[lower_bound, upper_bound]`
- whether to hold the norm factor constant ("Fixed")
The last setting is not yet propagated through `pyhf` to the fit, see https://github.com/scikit-hep/pyhf/issues/739 and https://github.com/scikit-hep/pyhf/pull/846.
Also adding some more config checks to ensure relevant options are specified in the config. Those checks need to be expanded in future updates.
=> feat: norm factor settings

.github/workflows/CI.yml, setup.py, src/cabinetry/configuration.py, src/cabinetry/contrib/matplotlib_visualize.py, src/cabinetry/template_builder.py, src/cabinetry/template_postprocessor.py, src/cabinetry/workspace.py, tests/conftest.py, tests/test_histo.py, tests/test_template_builder.py, tests/test_workspace.py
Adding `flake8-bugbear` and `flake8-import-order` to the CI and setup as [recommended by Scikit-HEP](https://scikit-hep.org/developer/style#flake8). This also fixes the warnings from those plugins.
Improving workspace unit testing to cover the new behavior introduced to fix the style issues.
=> style: flake8 plugins

.github/workflows/CI.yml, example.py, setup.cfg, setup.py, tests/test_configuration.py, tests/test_histo.py, tests/test_template_builder.py, tests/test_workspace.py, util/create_ntuples.py
Creating `setup.cfg` to store configuration for `pytest`, `flake8` and `mypy`. With `pytest` 6.0 it will be possible to move the options to `pyproject.toml` instead, see https://docs.pytest.org/en/latest/customize.html#pyproject-toml.
=> chore: moving options to setup.cfg

config_example.yml, src/cabinetry/configuration.py, src/cabinetry/histo.py, src/cabinetry/template_builder.py, src/cabinetry/template_postprocessor.py, src/cabinetry/workspace.py, tests/test_configuration.py, tests/test_integration.py, tests/test_template_builder.py, tests/test_template_postprocessor.py, tests/test_workspace.py, util/create_ntuples.py
Refactoring the template management to support a more generic set of systematics built from two templates without symmetrization. The new approach in the config is to use the same selections / weights / samples as in the associated nominal sample, but then to override them in the template definition. The override is specified in dicts associated to each template.
Expanding the config and ntuple creation script to test the new behavior. The ntuple script will have to be refactored in the future to scale better to more complex inputs.
=> feat: generic two-sided systematics

.github/workflows/CI.yml, .gitignore, .pre-commit-config.yaml, setup.cfg, setup.py, src/cabinetry/__init__.py, src/cabinetry/configuration.py, src/cabinetry/contrib/histogram_creation.py, src/cabinetry/contrib/matplotlib_visualize.py, src/cabinetry/fit.py, src/cabinetry/histo.py, src/cabinetry/template_builder.py, src/cabinetry/template_postprocessor.py, src/cabinetry/visualize.py, src/cabinetry/workspace.py
Adding type hints to `cabinetry`. For now they cover function arguments and return values. Checking is done mostly with `mypy`, for which configuration is added to `setup.cfg`. Two settings there are commented out, to be uncommented later when the remaining warnings can be resolved (those warnings are harmless for now).
Adding `mypy` to the CI for type checks.
Adding `mypy` and `flake8` to `pre-commit`.
The type hints uncovered some mistakes in the docstrings, which are fixed.
Besides `mypy`, `pytype` was also used to analyze `cabinetry`. `pytype` discovered another issue that `mypy` did not flag, but is slower to run. Should consider adding it to the CI eventually.
see also https://www.python.org/dev/peps/pep-0484/, https://www.python.org/dev/peps/pep-0526
=> feat: type hints

.github/workflows/CI.yml, .gitignore, setup.cfg, setup.py, src/cabinetry/configuration.py, src/cabinetry/schemas/config.json, tests/test_configuration.py
Adding a JSON schema https://json-schema.org/ for the `cabinetry` configuration. When reading a config file, it is validated against the schema.
Switching from using `pip install -e .` to `pip install .` in the CI to make sure it fails if required package data is not included.
=> feat: json schema for config

docs/api.rst, docs/conf.py, docs/config.rst, docs/index.rst, setup.py
Adding the config schema introduced in #69 to the docs built with sphinx, plus minor cleanup of the docs.
=> docs: config schema

config_example.yml, src/cabinetry/contrib/histogram_creation.py, src/cabinetry/template_builder.py, tests/contrib/test_histogram_creation.py
`uproot4` supports parsing python expressions in `TTree.arrays` through `uproot4.compute.python.ComputePython`. This small update makes use of this functionality to support parsing expressions (and calculating the results) for the variable to bin in (`Region` setting) and all weight settings.
=> feat: expressions for variables and weights

.readthedocs.yml, README.md, docs/index.rst
Setting up readthedocs https://docs.readthedocs.io/en/stable/index.html to host `cabinetry` documentation.
=> docs: providing documentation on readthedocs

example.py, setup.py, src/cabinetry/fit.py, src/cabinetry/visualize.py, tests/test_fit.py, tests/test_integration.py, tests/test_visualize.py
Following the `pyhf` refactor https://github.com/scikit-hep/pyhf/pull/951, switch to using the new `return_result_obj=True` keyword to obtain additional information from the minimizer. Also raise the minimum `pyhf` version to 0.5.0, which is the first version to include this API update.
In addition, adding pull plot / correlation matrix plot to the example.
Temporarily fixing the `boost-histogram` version until https://github.com/scikit-hep/boost-histogram/issues/437 is resolved.
=> refactor: use new pyhf optimizer API

.pre-commit-config.yaml, setup.cfg, setup.py
Adding `flake8-print` to setup extras and pre-commit to prevent accidental commits of print statements to the library.
=> chore: flake8-print checks

setup.py, src/cabinetry/__init__.py
Updating version for next tag / pypi release, and adding author name to setup. Also removing version restriction for `boost-histogram` implemented in #75, as the latest version is fixed.
=> chore: updating version to 0.0.5

setup.cfg, setup.py, src/cabinetry/configuration.py, src/cabinetry/contrib/histogram_creation.py, src/cabinetry/contrib/matplotlib_visualize.py, src/cabinetry/histo.py, src/cabinetry/template_builder.py, src/cabinetry/template_postprocessor.py, src/cabinetry/visualize.py, src/cabinetry/workspace.py, tests/contrib/test_histogram_creation.py, tests/contrib/test_matplotlib_visualize.py, tests/test_configuration.py, tests/test_fit.py, tests/test_template_builder.py, tests/test_visualize.py, tests/test_workspace.py
Adding [typeguard](https://typeguard.readthedocs.io/en/latest/) to setup extras and enabling running it with `pytest`. It can also be used during runtime via the import hook
```
from typeguard.importhook import install_import_hook
install_import_hook("cabinetry")
import cabinetry
```
Fixing all issues raised by `typeguard`.
Also refactoring the path handling: the user-facing API should accept paths as `Union[str, pathlib.Path]`.
=> test: fix issues raised by typeguard

config_example.yml, setup.py, src/cabinetry/fit.py, src/cabinetry/schemas/config.json, src/cabinetry/workspace.py, tests/test_fit.py, tests/test_workspace.py
Adding a new config option to fix parameters:
```yaml
General:
Fixed: [{Name: "Signal_norm", Value: 0.3}]
```
Workspaces built from the config contain the information about fixed parameters. Make use of https://github.com/scikit-hep/pyhf/pull/989 to read fixed parameters from the workspace and propagate that information to Minuit in `custom_fit`. Raising minimum `pyhf` version to 0.5.1 to support this. At the moment only `fit.custom_fit` respects fixed parameters, that will change eventually (https://github.com/scikit-hep/pyhf/pull/846).
This does not include improvements for plots to handle constant parameters.
=> feat: support fixed parameters

docs/advanced.rst, docs/api.rst, docs/index.rst, setup.cfg, src/cabinetry/__init__.py, src/cabinetry/route.py, src/cabinetry/template_builder.py, src/cabinetry/template_postprocessor.py, tests/test_configuration.py, tests/test_histo.py, tests/test_route.py, tests/test_template_builder.py, tests/test_template_postprocessor.py
With this update, template histograms are controlled from a new `route` module. This enables user-defined overrides for template histogram building.
The `route` module takes care of looping over templates and determining which function to apply to which template. A new decorator `@register_template_builder` allows users to define their own function that builds histograms, and this function is applied when matching the specified patterns.
Example:
```python
my_router = cabinetry.route.Router()
@my_router.register_template_builder(sample_name="Data")
def build_data_hist(reg: dict, sam: dict, sys: dict, tem: str) -> bh.Histogram:
hist = bh.Histogram(
bh.axis.Variable(reg["Binning"], underflow=False, overflow=False),
storage=bh.storage.Weight(),
)
yields = np.asarray([100, 102, 103, 104]) …
```
=> feat: user-defined overrides for template histogram handling

src/cabinetry/fit.py, tests/test_fit.py
Always run the Minuit HESSE algorithm after MIGRAD in `cabinetry.fit.custom_fit`. Section 7.2 in https://root.cern.ch/download/minuit.pdf describes the differences.
=> feat: always calculate Hessian

docs/advanced.rst, docs/cli.rst, docs/conf.py, docs/config.rst, docs/index.rst, setup.cfg, setup.py, src/cabinetry/cli/__init__.py, src/cabinetry/route.py, src/cabinetry/template_builder.py, src/cabinetry/template_postprocessor.py, tests/cli/test_cli.py, tests/test_template_builder.py, tests/test_visualize.py
Adding a basic CLI built with `click`. Documentation is added via `sphinx-click`. The entrypoint to the CLI is `cabinetry`, `cabinetry --help` to see the available commands.
Fixing inline code formatting by using two backticks instead of one.
=> feat: command-line interface

README.md, docs/index.rst
Adding a new badge to the readme:
[![NSF-1836650](https://img.shields.io/badge/NSF-1836650-blue.svg)](https://nsf.gov/awardsearch/showAward?AWD_ID=1836650)
to help with tracking of NSF funded projects via http://throughputdb.com/.
=> docs: NSF badge in readme

src/cabinetry/workspace.py, tests/test_workspace.py
Moving functionality for construction a `pyhf` style workspace into a new `WorkspaceBuilder` class to have it all grouped together. Workspaces can still be built via `cabinetry.workspace.build` after this change.
=> refactor: workspace builder class

config_example.yml, example.py, src/cabinetry/cli/__init__.py, src/cabinetry/schemas/config.json, src/cabinetry/template_builder.py, src/cabinetry/template_postprocessor.py, src/cabinetry/visualize.py, src/cabinetry/workspace.py, tests/cli/test_cli.py, tests/test_configuration.py, tests/test_integration.py, tests/test_template_builder.py, tests/test_template_postprocessor.py, tests/test_visualize.py, tests/test_workspace.py
Adding a new mandatory configuration file option `HistogramFolder` under `General`:
```yaml
General:
HistogramFolder: "histograms/"
```
This contains the path to the folder where all histograms are saved to and read from.
Switch to using `autospec=True` in CLI unit tests to catch changes in public API.
=> feat: adding histogram folder to config

setup.py, src/cabinetry/__init__.py
Moving from minor version 0 to 1, and pre-alpha to alpha. The most important change between 0.0.5 and 0.1.0 is the possibility of user-defined template histogram building overrides in #78.
=> chore: updating version to 0.1.0

src/cabinetry/workspace.py, tests/test_workspace.py
The observation dicts written to the `pyhf` workspace did not update properly when using more than one channel. This is fixed, and a test is added that can catch such an issue in the future.
=> fix: observed data in multiple regions

src/cabinetry/fit.py, src/cabinetry/visualize.py, tests/test_fit.py, tests/test_visualize.py
The pull plot functionality so far allowed to manually exclude parameters. This adds automatic removal of MC statistical uncertainties (labels starting with "staterror_") from the plot. Such parameters are centered around 1 and do not have unit width, so they make less sense to put on the same plot as other parameters with associated unit Gaussian constraint term.
Also fixing fit result reporting to have an extra space that allows negative fitted values to line up with positive ones in the log.
=> feat: removing staterrors from pull plot

docs/advanced.rst, setup.cfg, src/cabinetry/contrib/histogram_creation.py
This update enables reading observables / weights from vectors. In ROOT syntax, this would look like
```yaml
Weight: weight[0]*other_weight
```
In `cabinetry` it has to be written like
```yaml
Weight: weight[:,0]*other_weight
```
This is due to `uproot4` interpreting the string as Python code. More details are provided in this `uproot4` issue: https://github.com/scikit-hep/uproot4/issues/72.
Adding a section in the sphinx docs that describes this difference.
=> feat: support reading vector branches

src/cabinetry/fit.py, tests/test_fit.py
Adding an `asimov` keyword arguments to fit functions, which enables fits to the Asimov dataset instead of observed data.
The approach may be refactored in the future depending on the `pyhf` API (see https://github.com/scikit-hep/pyhf/issues/1029).
=> feat: Asimov fits

config_example.yml, src/cabinetry/schemas/config.json, src/cabinetry/template_builder.py, src/cabinetry/visualize.py, tests/test_configuration.py, tests/test_template_builder.py
Creating a new `General` config option: `InputPath`, which specifies the path to input ntuples. It can contain two placeholders: `{RegionPath}` and `{SamplePath}`, which are filled in by the respective settings `RegionPath` and `SamplePath` in the `Regions:` and `Samples:` lists in the config. The `{SamplePath}` placeholder can also be overridden for systematic uncertainties, with the `SamplePath` option.
resolves #16
This update enables most of the setups described in #16. For file structures that cannot be captured with these configuration options, #78 allows to handle the whole histogram creation process with user-defined python functions. It may turn out in the future that a central implementation of additional functionality is useful, the issue can then be revisited.
=> feat: more flexible input file path handling

.pre-commit-config.yaml, setup.py, src/cabinetry/cli/__init__.py, src/cabinetry/contrib/matplotlib_visualize.py, src/cabinetry/route.py, src/cabinetry/template_builder.py, src/cabinetry/workspace.py, tests/test_histo.py, tests/test_route.py, tests/test_template_builder.py, tests/test_template_postprocessor.py, tests/test_visualize.py
Updating the formatting to the latest [black](https://github.com/psf/black) tag `20.8b1`. Some trailing commas needed to be removed by hand to not force function arguments to be spread out across different lines. Pinning the `black` version in `pre-commit` and in the setup extras to `20.8b1`.
=> style: update to black 20.8 formatting

setup.cfg, setup.py
Moving metadata from `setup.py` to `setup.cfg` using [setup-py-upgrade](https://github.com/asottile/setup-py-upgrade).
Removing `python_version>='3.6'` for `black`, since `cabinetry` is Python >=3.6 only.
=> chore: moving metadata to setup.cfg

src/cabinetry/fit.py, src/cabinetry/visualize.py, tests/test_fit.py
Set the initial step size for fixed parameters in `custom_fit` to 0.0, which causes the post-fit parameter uncertainty to be 0.0. Affected parameters will automatically be pruned from the pull plot. Switch to using `skip_fixed=False` for the correlation matrix, to include rows/columns for fixed parameters (with all values set to 0.0). These parameters are automatically pruned from the correlation matrix visualization.
this implements the plot improvements mentioned in #82
=> feat: skip fixed parameters in pull plot and correlation matrix

util/create_ntuples.py
The ntuple creation script in `util` includes visualizes of the distributions it produces. This is now disabled by default, and can be re-enabled with the keyword argument `visualize`.
=> feat: visualization of ntuple creation utility can be disabled

setup.cfg, src/cabinetry/__init__.py
Updating version to allow for a new `cabinetry` release that includes pre- and post-fit plots introduced in #96.
=> chore: updating version to 0.1.2

src/cabinetry/fit.py, src/cabinetry/model_utils.py, src/cabinetry/visualize.py, src/cabinetry/workspace.py, tests/test_fit.py, tests/test_model_utils.py
Moving model construction from workspace into a function. Allowing for model-reuse, and moving Asimov data generation to the `model_utils` module.
`fit.custom_fit` is removed, and the functionality is instead accessed via `fit.fit(..., custom=True)`.
The new `model_utils.model_and_data` has a `with_aux` keyword argument that defaults to `True`, which is also added to `model_utils.build_Asimov_data`.
=> refactor: model building and model reuse

tests/test_integration.py, util/create_ntuples.py
Updating the integration test to use the histograms saved under `tmp_path`, rather than the histograms created by running `example.py` in an earlier CI step.
=> test: integration test isolation

setup.cfg, setup.py
Fixes #112.
#96 introduce a dependency on `awkward1`, which was so far only installed via the `contrib` setup extra. It is now removed from that setup extra and instead added as a core dependency.
=> fix: make awkward1 core dependency

src/cabinetry/contrib/matplotlib_visualize.py, util/create_ntuples.py
When visualizing a lot of templates, `matplotlib` printed a warning about many figures being open at once. This closes all figures after saving, since they are not needed anymore after that point.
=> fix: close matplotlib figures after saving

config_example.yml, docs/advanced.rst, docs/api.rst, docs/cli.rst, docs/config.rst, docs/core.rst, docs/index.rst, setup.cfg, setup.py, src/cabinetry/configuration.py, src/cabinetry/contrib/histogram_creation.py, src/cabinetry/schemas/config.json, src/cabinetry/template_builder.py, tests/contrib/test_histogram_creation.py, tests/test_configuration.py, tests/test_integration.py, tests/test_template_builder.py
Updates the `uproot` backend for ntuple reading to support building histograms from multiple input samples. It is now possible to use wildcards in the input paths, and lists for `SamplePaths`. A new section in [the docs](http://cabinetry.readthedocs.io/) explains the functionality.
**Breaking change:** The `SamplePath` option is renamed to `SamplePaths`. It takes either a single path, or a list of paths. If a list is specified, the sample histogram is built by combining the contributions from all files in the list. The entries of the list may have wildcards (with `*`).
Fixing systematic template overrides for `RegionPath`, which did not work before.
Raising minimum `uproot4` version to 0.0.19, which fixes a bug with lists in `uproot4.iterate`.
=> feat: support reading multiple input files per sample

README.md, example.py, src/cabinetry/cli/__init__.py, src/cabinetry/configuration.py, src/cabinetry/contrib/__init__.py, src/cabinetry/histo.py, src/cabinetry/model_utils.py, src/cabinetry/route.py, src/cabinetry/template_builder.py, src/cabinetry/template_postprocessor.py, tests/cli/test_cli.py, tests/test_configuration.py, tests/test_integration.py
**Breaking change:** renaming `configuration.read` to `configuration.load`.
Also updating docstrings to have a full sentence on one line as a summary. This resolves many issues flagged by
```
pydocstyle --convention google src/cabinetry/
```
=> refactor: configuration loading

src/cabinetry/fit.py, src/cabinetry/model_utils.py, src/cabinetry/visualize.py, tests/conftest.py, tests/test_fit.py, tests/test_integration.py, tests/test_model_utils.py, tests/test_visualize.py
Adding new `fit.ranking` to calculate the impact of a nuisance parameter on a parameter of interest. The results are saved in a new `fit.RankingResults` class, and `visualize.ranking` is refactored to take this as input. The ranking visualization (#97) also no longer centers staterror parameters around 0, and no longer removes the parameter of interest from bestfit/uncertainty/labels (done now in `fit.ranking`).
The post-fit impact calculation agrees for both observed data and Asimov with an independent implementation.
Splitting up functionality in `model_utils.get_asimov_parameters`, which now only returns the parameter values. The pre-fit parameter uncertainties are provided by `model_utils.get_prefit_uncertainties` instead.
Closes #110.
=> feat: nuisance parameter ranking

setup.cfg, src/cabinetry/__init__.py
Updating version to 0.1.3. Includes a fix to make `awkward1` a core dependency and likelihood scans.
=> chore: updating version to 0.1.3

src/cabinetry/cli/__init__.py, src/cabinetry/fit.py, src/cabinetry/visualize.py, tests/cli/test_cli.py
Adding nuisance parameter ranking and likelihood scan to the command line interface, see:
- `cabinetry ranking --help`
- `cabinetry scan --help`
Two small fixes: comparisons to None via `is None`.
=> feat: command line interface for ranking and scan

.github/workflows/dependencies-head.yml
This PR is a migration of https://github.com/scikit-hep/pyhf/pull/1071 and adds nightly tests that run at the `HEAD` of dependencies that are the most reasonable to check and interact with. If breaking changes are detected in these dependencies at their `HEAD` then there should be time to either proactively address this in `cabinetry` or work with the dependency dev team to mitigate them. They can also be run on demand with workflow dispatch.
Note that these tests only run on CRON jobs and on demand, but never on pushes of PRs.
Example workflow: https://github.com/matthewfeickert/cabinetry/actions/runs/266365012
**Suggested squash and merge commit message**
```
* Add nightly tests to run test suite at HEAD of dependencies
- Use as early alert for breaking changes in dependencies
- Run for …
```
=> ci: Add nightly tests using HEAD of dependencies

docs/advanced.rst, src/cabinetry/fit.py, src/cabinetry/model_utils.py, tests/test_fit.py, tests/test_model_utils.py
Parameters that are set to be held constant in fits have no impact on the parameter of interest by construction. This skips the fit to calculate the impact, which instead is set to 0 directly.
Also changing the pre-fit uncertainty assigned to fixed parameters, which is no 0 (as is the post-fit uncertainty).
Adding a section in the docs to explain the behavior of fixed parameters.
=> feat: skip ranking for fixed parameters

setup.cfg, src/cabinetry/configuration.py, src/cabinetry/contrib/matplotlib_visualize.py, src/cabinetry/fit.py, src/cabinetry/histo.py, src/cabinetry/model_utils.py, src/cabinetry/route.py, src/cabinetry/template_builder.py, src/cabinetry/visualize.py, src/cabinetry/workspace.py, tests/test_histo.py, tests/test_integration.py, tests/test_route.py
The code is formatted by `black` to have a maximum line length of 88 characters. The current version of `black` does not re-format strings or comments. This updates all comments / docstrings to be limited to 88 characters per line, and re-formats strings as well. The `flake8` setting for `max-line-length` is updated to 88.
=> style: consistent maximum line length

src/cabinetry/model_utils.py, src/cabinetry/visualize.py, tests/test_model_utils.py
This fixes the data/MC visualizations for workspaces with at least three channels. The split of `pyhf.pdf.Model.expected_data`  into channels was using wrong indices if more than two channels are in the workspace. This produced a crash.
=> fix: visualization of three and more channels

src/cabinetry/configuration.py, src/cabinetry/contrib/histogram_creation.py, src/cabinetry/contrib/matplotlib_visualize.py, src/cabinetry/histo.py, src/cabinetry/model_utils.py, src/cabinetry/route.py, src/cabinetry/template_builder.py, src/cabinetry/template_postprocessor.py, src/cabinetry/visualize.py, src/cabinetry/workspace.py
Updating docstrings to maximum line length of 88, which was introduced in #128.
=> style: docstring line length

src/cabinetry/model_utils.py, tests/test_model_utils.py
The nominal prediction from `pyhf.Model.nominal_rates` does not treat initial values for `normfactors` set in the workspace as nominal (see https://github.com/scikit-hep/pyhf/issues/1106). Since there is no other way to specify the nominal values for these unconstrained parameters, `cabinetry` treats the initial value as the nominal value. This updates the Asimov dataset generation to achieve the desired behavior.
=> feat: treat initial normalization factor settings as nominal values

setup.cfg, src/cabinetry/model_utils.py
In https://github.com/scikit-hep/pyhf/pull/1110, `paramset.fixed` was renamed to `paramset.suggested_fixed`. This change will go into `pyhf` 0.5.3 when it is released.
This updates the naming and raises minimum `pyhf` version to 0.5.3.
This pull request should be merged directly after the next version of `pyhf` is released.
=> fix: pyhf 0.5.3 compatibility

docs/cli.rst, src/cabinetry/cli/__init__.py, src/cabinetry/workspace.py, tests/cli/test_cli.py
Allows using `-` to refer to stdin/stdout for workspaces and the `cabinetry` configuration. See the [click file argument documentation](https://click.palletsprojects.com/en/7.x/arguments/#file-arguments).
Examples:
```bash
cat config_example.yml | cabinetry workspace - workspaces/example_workspace.json
cat workspaces/example_workspace.json | cabinetry fit -
cabinetry workspace config_example.yml -
```
resolves #141
=> feat: support stdin/stdout piping in command line interface

README.md, example.py, src/cabinetry/visualize.py, tests/test_visualize.py
This adds `"figures"` as default value for the output folder of visualizations done through the `visualize` module. Previously the  `figure_folder` was a required argument. The default can be overridden via the `figure_folder` keyword argument.
**breaking change:** The order of arguments for `visualize.data_MC` changed: the workspace specification is now the second required argument, while the figure output folder is the third function argument and optional.
=> feat: default output folder for visualizations

src/cabinetry/fit.py, tests/test_fit.py
This adds support for fixed parameters and initial parameter value settings to `fit._fit_model_pyhf`, which uses the `pyhf.infer` API for MLE fits. With this addition, the interface matches the `fit._fit_model_custom` implementations (which allows for direct control over `iminuit` internally).
Sets up infrastructure needed for #131.
=> feat: extend parameter control when using pyhf.infer

src/cabinetry/fit.py, tests/test_fit.py
This adds `fit._fit_model` as a common entry point to call either `fit._fit_model_pyhf` (maximum likelihood fit using `pyhf.infer` API) or `fit._fit_model_custom` (maximum likelihood fit using `iminuit` directly), depending on the value of the `custom` keyword argument (defaults to `False`: use `pyhf.infer` API).
Allows for the addition of ranking / scan through the `pyhf.infer` API in the future with this new interface. Currently ranking / scan fits make use of `fit._fit_model_custom` only.
=> refactor: common entry point for maximum likelihood fits

src/cabinetry/fit.py, src/cabinetry/model_utils.py, tests/test_fit.py, tests/test_integration.py
Make use of the new maximum likelihood entry point added in #146 to support using the `pyhf.infer` API for fits needed in nuisance parameter ranking and parameter scans.
**breaking change:** rename `custom` keyword argument (switches between `pyhf.infer` and `iminuit`) to `custom_fit`
also included: unrelated minor update for consistent f-string usage
=> feat: support pyhf.infer fits for ranking and parameter scans

src/cabinetry/fit.py
Better type hints for `iminuit.Minuit` objects. This is needed for compatibility with the upcoming `iminuit` v2 based on `pybind11`.
=> fix: iminuit.Minuit type hints

.pre-commit-config.yaml, setup.py
Add `pyupgrade` to the pre-commit hooks to help move the codebase along as support for older versions of Python are dropped in time to use newer features and to shed older syntax.
For an example of some of the benefits c.f. https://github.com/scikit-hep/pyhf/pull/1164.
```
* Add pyupgrade v2.7.4 to pre-commit hooks
- Run with --py36-plus option
* Apply pyupgrade to codebase
```
=> chore: Add pyupgrade to pre-commit hooks

setup.cfg, src/cabinetry/fit.py, src/cabinetry/histo.py, src/cabinetry/model_utils.py, tests/test_fit.py, tests/test_integration.py, tests/test_model_utils.py
Adding a goodness-of-fit-calculation based on the [saturated model](http://www.physics.ucla.edu/~cousins/stats/cousins_saturated.pdf). A chi^2 test is performed using the likelihood ratio between the nominal fit and the saturated likelihood. The resulting p-value is added to the `FitResults` object, and defaults to `-1` if the calculation is not performed.
This implementation makes use of https://github.com/scikit-hep/pyhf/issues/1169, enabling a significant simplification over the previous implementation(which was complete as of 90a40b2e21b4a1be17ea325d12323f1b1ffaeaa6, related issue https://github.com/scikit-hep/pyhf/issues/1098 would have allowed for an alternative implementation with a `model_utils` function that translates model -> saturated model).
resolves #127
=> feat: goodness of fit test with saturated model

src/cabinetry/fit.py, src/cabinetry/model_utils.py, tests/test_fit.py, tests/test_model_utils.py
When attempting to run MINOS with parameters that are unknown (e.g. due to a typo), show an error and skip the unknown parameter instead of failing silently or crashing. This also adds a convenience function `model_utils._get_parameter_index` to obtain the index of a parameter (known by name) within a model.
=> feat: better handling of unknown parameters when running MINOS

src/cabinetry/cli/__init__.py, tests/cli/test_cli.py
Adding command line interface for upper parameter limits. See `cabinetry limit --help` for details.
=> feat: command line interface for parameter limits

setup.cfg, setup.py, tests/conftest.py, util/create_ntuples.py
In preparation for the migration `uproot4` -> `uproot`, the "old" `uproot` migrates to `uproot3`. Since `uproot3` is available now (https://pypi.org/project/uproot3/), this updates `uproot` -> `uproot3`. The migration `uproot4` -> `uproot` will follow later. 
Also adding upper limits for the `pyhf` and `iminuit` versions. Compatibility with `pyhf` 0.6 will require updates to `cabinetry` (#150/#156), and the interface changes in `iminuit` 2.0 will also require an update to `cabinetry`.
=> fix: uproot package name migration to uproot3 

.github/workflows/dependencies-head.yml, README.md, docs/advanced.rst, setup.cfg, setup.py, src/cabinetry/contrib/histogram_creation.py, src/cabinetry/model_utils.py, tests/test_model_utils.py
This completes the name transitions `awkward1` -> `awkward>=1.0.0` and `uproot4` -> `uproot>=4.0.0`. The switch to `pyhf` [0.5.4](https://github.com/scikit-hep/pyhf/releases/tag/v0.5.4) makes this possible, since in that update `pyhf` switches to `uproot3` to access the old `uproot` API (thereby avoiding name space conflicts under the `uproot` package name).
In particular, this allows use of `cabinetry` together with the `pyhf` `xmlio` setup extra again.
related: #157
=> fix: finalize uproot/awkward name migration and update to pyhf 0.5.4

setup.cfg, src/cabinetry/__init__.py
Updating to 0.1.7 to avoid namespace collisions with the `uproot` package when using `pyhf` with `xmlio` setup extra (see #164).
=> chore: updating version to 0.1.7

.github/workflows/dependencies-head.yml
This is a port of https://github.com/scikit-hep/pyhf/pull/1227 to make sure that the HEAD of dependencies workflow it operating in the way it is expected to.
```
* pip uninstall the dependency that is being tested before installing from the HEAD of version control
- Has been shown for iminuit to be required to properly test the HEAD of the default repo branch
```
=> ci: Uninstall dependencies before installed HEAD versions

setup.cfg, setup.py
Instead of listing all hard requirements out explicitly, this PR removes those dependencies from the list that `pyhf` installs through its own `install_requires`. It additionally constrains the ranges of libraries using the [compatible release synatx of PEP 440](https://www.python.org/dev/peps/pep-0440/#compatible-release).
This probably isn't ever going to be an issue, but with `pip` `v20.3` and the addition to the dependency resolver it probably helps to have better constraints on _ranges_ of dependencies. 
```
* Simplify install_requires by requiring pyhf control dependencies it installs
* Use compatible release syntax (~=) to constrain dependencies to release ranges
```
=> chore: Simplify install_requires and use compatible release syntax

setup.cfg, src/cabinetry/tabulate.py, tests/test_tabulate.py
Yield table entries for bins after the first bin of a region were accidentally overwritten when multiple multi-bin regions were used. This was caused by the table header (used as dict key) not being unique. This changes the header to make it unique, by including the region name in each header (previously omitted since it seemed superfluous).
resolves #167
Previously failed `mypy` since stubs for `tabulate` were missing the `Dict[str, str]` type for headers, fixed with https://github.com/python/typeshed/pull/4835.
=> fix: yield tables for multiple multi-bin regions

src/cabinetry/fit.py, src/cabinetry/visualize.py, tests/test_visualize.py
The `exclude_list` keyword argument in `cabinetry.visualize.pulls` used to require a list. This adds support for strings (single parameter) and tuples. The old name does not make sense anymore with the support of these types, so the argument is renamed and now called `exclude`.
Also updating typing for `minos` parameter that contains the parameters to run MINOS on. With this, `cabinetry.fit.fit` now properly supports tuples for this parameter. They already worked fine before, but not with runtime type checks.
**Breaking change:**
- `cabinetry.visualize.pulls` keyword argument `exclude_list` renamed to `exclude`
=> feat: more flexibility in parameter exclusion from pull plots

docs/index.rst, setup.cfg, src/cabinetry/fit.py, tests/test_fit.py, tests/test_integration.py
The previous implementation to find CLs=0.05 crossings minimized `|CLs-0.05|`. This was not very efficient. A more efficient approach is using Brent's method to find roots `CLs-0.05 = 0`. This requires a suitable starting bracket `[a, b]` where `f(a)` and `f(b)` have different signs. In this case, two POI values are needed, where one is below the limit and one above.
For further performance improvements, caching is added to skip the hypothesis test for POI values that have been tested before. Typically that skips two tests per limit (10 total for observed, expected and expected +/- 1,2 sigma).
The full test suite is around 25% faster with this change.
The new method is more precise in the examples tested.
A new keyword argument `maxiter` allows to set the maximum amount of iterations …
=> feat: root finding for faster limit convergence

src/cabinetry/fit.py, tests/test_fit.py
Instead of defaulting to an upper bracket of `10.0` in the limit calculation, use the upper bound on the POI specified in the measurement (in the workspace).
=> feat: take upper bracket default for limit from measurement

src/cabinetry/fit.py, tests/test_fit.py, tests/test_integration.py
Make better use of [Python's built-in string formatting](https://docs.python.org/3/library/string.html#format-specification-mini-language):
- `<` instead of `ljust`
- empty space to align positive and negative numbers (leaving space for minus sign)
- `%` for percentages
- `+` to force sign for positive values as well
=> refactor: string formatting

README.md
The relative link to the logo in `docs/` breaks the visualization of the logo on [PyPI](https://pypi.org/project/cabinetry/). Switch to using the logo from https://raw.githubusercontent.com, which should allow the logo to also show up on PyPI. The logo shown there will break if the logo is renamed/moved in the future.
=> docs: change logo location for PyPI rendering

README.md, example.py, src/cabinetry/fit.py, src/cabinetry/visualize.py, tests/test_visualize.py
This updates the `visualize.data_MC` API to use `model, data` arguments instead of a workspace specification (like #183 did for the `fit` API). The cabinetry `config` argument is no longer required, but an optional keyword argument. If no config file is supplied, plots can still be created with the defaults: axis label "bin", bin width 1 on the x-axis. Since the `pyhf` model does not store bin edge information or variable names, no further information can be extracted by default.
This new API allows for easy visualization of  models that were produced without `cabinetry` (and for which consequently no `cabinetry` config may exist).
**Breaking changes:**
- refactored `visualize.data_MC`: workspace specification argument removed, now requires `model, data` (`pyhf` model and data with or …
=> feat: data/MC plots without configuration file

src/cabinetry/contrib/matplotlib_visualize.py, tests/contrib/test_matplotlib_visualize.py
The "68% CL" / "95% CL" text in the likelihood scan visualization was previously always drawn and independent of the y-axis range. For narrow scans around the minimum, the log likelihood offset may not reach 1 or 4. This suppresses the display of the corresponding CL annotations in this case to fix the figure layout.
=> fix: likelihood scan visualization layout for small NLL variations

.github/workflows/CI.yml
Recent commits occasionally skip `matplotlib` visualization tests in the CI with:
> SKIPPED [7] ../../../../../opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/matplotlib/testing/compare.py:279: Don't know how to convert .pdf files to png
See for example f9d8a999004df01d13b77f7d36b8b041198f7396 where the tests worked, and the following a8f3942b7ba6d171906663ab731433d47888edce where they were skipped. This leads to fluctuating coverage.
This Installation of `ghostscript` is now done in the CI to resolve the problem.
=> ci: install ghostscript for pdf conversion

src/cabinetry/cli/__init__.py, src/cabinetry/fit.py, tests/cli/test_cli.py, tests/test_fit.py, tests/test_integration.py
The `fit_results` argument in `fit.ranking` is used as the reference to determine nuisance parameter variations and the reference POI value for impact calculations. This makes the argument an optional keyword argument instead. If not provided, the nominal fit is performed automatically.
**Breaking change:**
- `fit_results` argument in `fit.ranking` is now a keyword argument (not breaking currently, but may become a breaking change in the future)
=> feat: make reference fit results in ranking optional

.pre-commit-config.yaml, setup.cfg, src/cabinetry/fit.py, src/cabinetry/smooth.py, src/cabinetry/visualize.py, tests/test_smooth.py
With `numpy` release 1.20, [it is now typed](https://numpy.org/doc/1.20/release/1.20.0-notes.html#numpy-is-now-typed). This results in some new things flagged by `mypy` that are fixed here.
Also fixes edge case where `smooth.smooth_353QH_twice` applied to `np.ndarray` with `int` `dtype` returns the wrong result due to rounding.
=> fix: numpy array smoothing and typing

src/cabinetry/model_utils.py, src/cabinetry/tabulate.py, src/cabinetry/visualize.py, tests/test_model_utils.py, tests/test_tabulate.py, tests/test_visualize.py
Added `tabulate._yields_per_channel` to build yield tables with yields per channel. These tables are shown when `visualize.data_MC` is called with `include_table=True` (the default). `model_utils.calculate_stdev` is expanded to include calculation of uncertainties for the sum of yields per channel.
resolves #158 
**breaking changes:**
- `model_utils.calculate_stdev` now returns a tuple: uncertainties for all bins per channel, and uncertainties for total yield in channel
- `tabulate. _yields` renamed to `tabulate._yields_per_bin`
=> feat: yields per region

.github/workflows/CI.yml, tests/test_integration.py
This disables the [`fail-fast`](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstrategyfail-fast) strategy in the CI. The jobs in the matrix of Python versions will not be stopped early if another job fails, which can be useful to catch potential differences between Python versions.
=> ci: do not cancel jobs early if another job fails

src/cabinetry/tabulate.py
#169 introduced a `# type: ignore` to skip `mypy` checking an argument type in a `tabulate.tabulate` call due to a bug in the `tabulate` type stubs. With `mypy` 0.800 the fix has been propagated and the check does no longer need to be skipped.
=> feat: mypy check for tabulate package

tests/test_integration.py
Adding pre- and post-fit data/MC plots to integration test to include a check of yield uncertainties in this test.
=> test: check yield uncertainties in integration test

.github/workflows/CI.yml, .pre-commit-config.yaml, pyproject.toml, setup.cfg
Following `pyhf` dropping support for Python 3.6 (https://github.com/scikit-hep/pyhf/pull/1272) in the upcoming 0.6 release, `cabinetry` will also drop 3.6 support in line with the [NEP schedule](https://numpy.org/neps/nep-0029-deprecation_policy.html#drop-schedule).
The minimum Python version is raised to 3.7, and the last `cabinetry` version to support Python 3.6 will likely be 0.1.8. Upcoming releases require at least version Python 3.7. Testing for Python 3.6 is also dropped.
Support for Python 3.9 will be added officially once `pyhf` supports it (it already seems useable on the `fix/pyhf-0.6-compatibility` branch).
resolves #192
=> build: drop support for Python 3.6

src/cabinetry/fit.py, tests/test_fit.py
The default lower parameter of interest (POI) bound in limit calculations through `fit.limit` used to be `0.01`. This is close to the lower POI bound of `0` that is used with the `qtilde` test statistic (see eq. 16 in https://arxiv.org/abs/1007.1727), and can lead to instabilities and `nan` CLs values (see https://github.com/scikit-hep/pyhf/issues/1278). This affects the simple example provided in this repository.
The lower bracket value is change from `0.01` to `0.1` to help avoid such instabilities with default parameter values. The `bracket` keyword argument is still available to specify custom lower and upper POI bracket values.
=> feat: update default bracket in limit calculation for stability

setup.py
The recent `typeguard` releases `2.11.0` and `2.11.1` cause errors in tests when type checking classes inheriting from `typing.NamedTuple` in Python 3.7 (and 3.6), as reported in https://github.com/agronholm/typeguard/issues/175. This restricts the version to `2.10.0` and below as a temporary fix.
=> fix: restrict typeguard version for NamedTuple compatibility

src/cabinetry/cli/__init__.py, src/cabinetry/fit.py, tests/cli/test_cli.py, tests/test_fit.py, tests/test_integration.py
This adds functionality to calculate observed/expected discovery significance for a positive signal via `fit.significance`. The implementation relies on https://github.com/scikit-hep/pyhf/pull/1232. This functionality is also available via the CLI with `cabinetry significance`.
A new class `fit.SignificanceResults` is used as a container storing results of a significance calculation (observed and expected p-value and significance).
Requires `pyhf` 0.6 and #156, which are both now available.
Also updates the Minuit verbosity through pyhf, now using the `iminuit` v2 API style.
closes #100
=> feat: discovery significance

setup.cfg, src/cabinetry/__init__.py
Updating minor version to `0.2.0`. This new version adopts the `pyhf` 0.6 and `iminuit` v2 APIs, drops support for Python 3.6, introduces changes to the `cabinetry.fit` API, and adds discovery significance calculation among other features.
=> chore: updating version to 0.2.0

setup.cfg, setup.py
Motivated by https://hynek.me/articles/semver-will-not-save-you/, this removes upper version limits for dependencies where internals are not heavily used. The two exception that retain the upper limit currently are
- `pyhf`: expect that breaking changes (for `cabinetry`) between minor versions are still likely,
- `boost_histogram`: will be updated after https://github.com/alexander-held/cabinetry/issues/201 is resolved.
Also slightly raises minimum required `pytest-cov` version for use with `no_cover`.
=> chore: remove upper version limits for dependencies

.pre-commit-config.yaml, src/cabinetry/cli/__init__.py, tests/cli/test_cli.py
Adds `cabinetry data-mc` to the command line interface. This allows accessing functionality from `cabinetry.visualize.data_MC` via the CLI.
- optional cabinetry config (for horizontal axis label / binning) via `--config`
- flag `--postfit` to draw post-fit model instead of pre-fit (performs required fit automatically)
- possibility to override figure folder for output via `--figfolder`
Also updates `pre-commit` via `pre-commit autoupdate`.
=> feat: command line interface for data-MC plots

.github/workflows/CI.yml, .pre-commit-config.yaml, setup.cfg, src/cabinetry/contrib/histogram_creation.py, src/cabinetry/histo.py, src/cabinetry/route.py, tests/test_histo.py, tests/test_route.py
This enables support for `boost-histogram>=1.0.0`. Subclassing `Histogram` requires a `family` keyword argument (optional starting with `boost-histogram` 1.0.1), and the `boost-histogram` library is now typed. 
resolves #201
```
* support and require boost-histogram>=1.0.0
* improved type checking via pre-commit
* added test for histogram properties
* skip mypy in CI for Python 3.7
```
For reading yields and variances, switch to using `h.values()` and `h.variances()` instead of `h.view().value` and `h.view().variance`. The `view()`-based method is still used for writing yields / variances directly.
Calling `numpy` functions with values/variances requires a `# type: ignore`, as does setting values via `view()`.
See https://github.com/scikit-hep/boost-histogram/issues/527 and …
=> feat: boost-histogram 1.0 compatibility and typing updates

src/cabinetry/route.py
#204 revealed a typing bug in `cabinetry.route`, since `bh.Histogram` is no longer considered `Any`. This fixes the bug:
- `register_template_builder` should only ever be used to decorate functions returning a histogram (so those functions should have type `UserTemplateFunc`)
- the `register_template_builder` function calls `_register_processor`, which also should handle functions of type `UserTemplateFunc`
- `_register_processor` uses `_register` which should follow the same logic
- since all `_find_match` uses the registered functions which are now all of type `UserTemplateFunc`, `_find_match` itself should also return a function of that type
`_find_match` (which returns a un-wrapped `UserTemplateFunc`) is only used via `_find_template_builder_match`, which returns a user-provided …
=> fix: typing for registering custom template builders

setup.py
`typeguard` 2.12.0 is affected by the same issue with `NamedTuple` as versions 2.11.*, so this skips 2.12 as dependency. See also #199.
=> fix: skip typeguard 2.12 for NamedTuple compatibility

.pre-commit-config.yaml, src/cabinetry/fit.py, tests/conftest.py, tests/test_fit.py
Fixes the goodness-of-fit calculation for models without auxiliary data and without constraint terms. Handles the split of data into main and auxiliary data depending on whether auxiliary data is present, and skips the constraint term calculation if no constraint term is present (https://github.com/scikit-hep/pyhf/issues/1390).
Also adds a warning for models for which the GOF cannot be calculated, either since the number of degrees of freedom is zero (nominal model should already result in perfect fit), or the model is over-parameterized (negative number of degrees of freedom).
resolves #206
=> fix: goodness-of-fit with no auxiliary data

.github/workflows/CI.yml
Codecov needs no token for public projects (since action version [1.0.6](https://github.com/codecov/codecov-action/releases/tag/v1.0.6)), so this token can be removed.
=> ci: remove Codecov token

src/cabinetry/configuration.py, src/cabinetry/route.py, src/cabinetry/schemas/config.json, src/cabinetry/template_postprocessor.py, src/cabinetry/workspace.py, tests/test_configuration.py, tests/test_route.py, tests/test_workspace.py
Addresses #214 in part. This adds a `Regions` property to samples, which allows specifying the regions that contain a given sample.
Also improves the error in `configuration.histogram_is_needed` when encountering an unknown systematic: switching to a `ValueError` and reporting the name of the unknown systematic.
=> feat: region-dependent samples

config_example.yml, src/cabinetry/configuration.py, src/cabinetry/schemas/config.json, src/cabinetry/template_postprocessor.py, src/cabinetry/workspace.py, tests/test_configuration.py, tests/test_route.py, tests/test_workspace.py
`Systematics` and `NormFactors` previously had a required `Samples` property to specify on which samples the modifier acts. This makes the property optional, and when not specified the modifier will act on all samples. Also unifies the functionality in the `configuration` module to avoid duplications due to the features required by #214, including harmonizing the `Samples` handling for smoothing.
partially addresses #214
**breaking changes**:
- `configuration.sample_affected_by_modifier` renamed to `configuration.sample_contains_modifier` to harmonize naming with `configuration.region_contains_sample` and the upcoming `configuration.region_contains_sample`
=> feat: make Samples property of modifiers optional

.pre-commit-config.yaml, setup.py
Removing pinning of `black` version in `contrib` setup extra, and running `pre-commit autoupdate`.
=> chore: remove black version restriction and update pre-commit hook versions

src/cabinetry/configuration.py, src/cabinetry/schemas/config.json, src/cabinetry/workspace.py, tests/test_configuration.py, tests/test_workspace.py
This adds a `Regions` property to systematics and normfactors to specify region dependence. When used, the modifiers only enter in the specified regions. Otherwise they enter all regions by default.
**breaking changes**:
- `workspace.WorkspaceBuilder.get_NF_modifiers` signature changed, now takes a `region` and `sample` argument (only used `sample` previously)
resolves #214
=> feat: region-dependent modifiers

setup.cfg, src/cabinetry/__init__.py
Updating to version `0.2.1`. This adds flexibility in model construction (samples and systematics with region dependence), CLI for data/MC plots, compatibility with the `boost-histogram` v1 API and fixes goodness-of-fit for models without auxiliary data.
=> chore: updating version to 0.2.1

tests/test_workspace.py
This adds a test for `workspace.WorkspaceBuilder.get_NormPlusShape_modifiers` and refactors `get_sys_modifiers`.
=> test: extend coverage for workspace building

.github/workflows/CI.yml, .pre-commit-config.yaml, setup.py
The recently released `typeguard` 2.12.1 does not work with`NamedTuple` in Python 3.6 and 3.7, so this skips all versions 2.12.*. Related: #209, #199.
The Codecov upload was broken with error message
```python
{'detail': ErrorDetail(string='Unable to locate build via Github Actions API. Please upload with the Codecov repository upload token to resolve issue.', code='not_found')}
```
so this adds back the Codecov token previously removed in #215 to fix this. #231 is therefore no longer needed.
=> fix: NamedTuple compatibility in typeguard, Codecov token for upload

.github/workflows/CI.yml, .pre-commit-config.yaml, pyproject.toml, setup.cfg, setup.py, src/cabinetry/cli/__init__.py, src/cabinetry/configuration.py, src/cabinetry/contrib/matplotlib_visualize.py, src/cabinetry/fit.py, src/cabinetry/visualize.py
With the release of [`mypy` 0.900](http://mypy-lang.blogspot.com/2021/06/mypy-0900-released.html), third party type stubs need to be separately installed. This affects `PyYAML` and `tabulate` in the case of `cabinetry`. The new `mypy` version also revealed a small typing issue in the CLI that is fixed here.
`pyhf` 0.6.1 caps `click` to version below 8.0, which means `types-click` would temporarily be required until the release of `pyhf` 0.6.2 when running `mypy` outside of pre-commit.
The solution adopted here for compatibility with `mypy` 0.900+ is instead to move `mypy` to only run via `pre-commit`. It is still possible to run it directly manually by installing `click` 8.0+ (manual installation will no longer be required in `pyhf` 0.6.2, where the cap will be removed).
`mypy` runs in …
=> fix: compatibility with mypy 0.900

src/cabinetry/cli/__init__.py
The `fit` function in the CLI has the structure
https://github.com/alexander-held/cabinetry/blob/d888ec054e080f474a12de6de375857631c55987/src/cabinetry/cli/__init__.py#L134-L137
and both branches are tested:
https://github.com/alexander-held/cabinetry/blob/d888ec054e080f474a12de6de375857631c55987/tests/cli/test_cli.py#L172-L182
In CI, where the coverage is calculated with Python 3.7, everything shows up as covered. When using Python 3.8 it does not. This is presumably due to a CPython optimization, and can seemingly be fixed by the addition of a `pass`:
https://github.com/alexander-held/cabinetry/blob/1a11641e214072c3922d7a1269304c97754496b8/src/cabinetry/cli/__init__.py#L138
This PR adds this `pass` and a link to a coverage issue which discusses what I believe is the same underlying …
=> fix: workaround for coverage bug

.github/workflows/CI.yml, setup.py, src/cabinetry/fit.py, src/cabinetry/model_utils.py, src/cabinetry/visualize.py, tests/conftest.py, tests/test_backends.py
`cabinetry` previously had the `numpy` backend for `pyhf` hardcoded. This PR removes this restriction, allowing users to call `pyhf.set_backend("jax")` etc. outside of `cabinetry` code. Fits via `cabinetry` will then respect the backend set. The return type of several `pyhf` functions is backend-dependent, so conversions to `numpy` are added where required. This allows for consistent types within `cabinetry`.
A new integration test is added for the backends other than `numpy`. Since this test is slow, it will only run via `pytest` if the new `--runslow` flag is used. The test ensures consistency of the two MLE fit implementations, and calls the relevant parts of the `cabinetry.fit` API where the different `pyhf` backends may return different results. It similarly calls the relevant …
=> feat: support all pyhf backends

example.py, src/cabinetry/__init__.py, tests/test_cabinetry.py, tests/test_configuration.py, tests/test_histo.py
Adds a new function `cabinetry.set_logging()` that sets up a basic customized log output. The logging is set to be verbose, with `DEBUG` level outputs for `cabinetry` and `INFO` for `pyhf`. This function also shows a basic example for how to customize logging if users wish to customize it themselves. In that case this function should not be called, as the logging can only be set up once.
=> feat: helper function for log formatting

.pre-commit-config.yaml, src/cabinetry/model_utils.py, tests/test_model_utils.py
The Asimov dataset generation used auxiliary data to determine suitable Asimov parameter values. This does not work for `shapesys` modifiers, where the auxiliary data is (nominal/uncertainty)^2. This PR fixes the behavior and introduces a simplified way to determine parameter settings without needing to refer to auxiliary data, but by using the modifier type instead.
The parameters need to be floats. If all are integers, the model uncertainty calculation via `model_utils.calculate_stdev` produced a different result due to `dtype` mismatch, example:
```python
>>> import numpy as np
>>> a = np.array([1,2])
>>> a[1] += 0.5
>>> a
array([1, 2])
```
Besides ensuring float returns from `get_asimov_parameters`, the up/down parameter variations in `model_utils.calculate_stdev` are now converted to …
=> fix: Asimov generation with shapesys modifiers

setup.cfg, src/cabinetry/__init__.py
Updating to version `0.2.2`. This adds support for all `pyhf` backends and a helper function for log formatting, and fixes Asimov generation with `shapesys` modifiers.
=> chore: updating version to 0.2.2

setup.cfg, src/cabinetry/contrib/matplotlib_visualize.py, src/cabinetry/visualize.py, tests/contrib/test_matplotlib_visualize.py, tests/test_integration.py, tests/test_visualize.py
#115 ensured that figures are closed immediately after saving them, which avoids memory issues when keeping many open figures around. This also prevents figures from being rendered in notebooks, which look for figures known to `matplotlib.pyplot` at the end of a cell. With all figures already closed, no figures are drawn.
This changes the default behavior again to not close figures. A new optional argument `close_figure` can be used in the `cabinetry.visualize` API to change back to the old behavior (via `close_figure=True`). This means that by default now figures will be drawn in notebooks again. Users may also use `matplotlib.pyplot.close("all")` anywhere to close all currently open figures.
The figure saving/closing is factored out into a separate function to avoid duplication in …
=> feat: notebook rendering for figures

src/cabinetry/model_utils.py, tests/conftest.py, tests/test_model_utils.py
#238 fixed the Asimov dataset generation (more precisely, the generation of the parameters used to produce the Asimov dataset) for `shapesys` modifiers and refactored the parameter determination mechanism. This refactor introduced a bug in the `lumi` modifier treatment: the corresponding parameter was initialized at 0. Instead, it should be initialized at the corresponding auxiliary data value.
In most scenarios the auxiliary data is likely `1.0`, but in principle it can be different. In that case, the parameter setting should match the auxiliary data, with an approach as the one used prior to #238 of matching auxiliary data and parameters. This more general treatment will be implemented in a separate PR -> tracked in #242.
Reverting back to the approach of reading out auxiliary data also …
=> fix: Asimov generation with lumi modifiers

README.md, docs/index.rst
Updating README text, removing some more general considerations that are better described in other places, in particular in the vCHEP paper. The vCHEP talk + paper and the PyHEP talk are also added to the documentation.
```
* updated readme text and added Zenodo badge
* added links to talks to documentation
```
=> docs: update readme and add talks to documentation

setup.cfg, src/cabinetry/__init__.py
Updating to version `0.2.3`. This update includes a few small changes in preparation of the [PyHEP 2021 talk on cabinetry](https://indico.cern.ch/event/1019958/contributions/4421868/). Figure rendering in notebooks is enabled again, Asimov dataset generation for `lumi` modifiers is fixed and the readme is updated.
```
* updating version to 0.2.3
```
=> chore: updating version to 0.2.3

.pre-commit-config.yaml, pyproject.toml, setup.cfg
Adds support for PEP 517/518 via settings in `pyproject.toml`. For more information, see links in #74 and
- [Scikit-HEP developer information](https://scikit-hep.org/developer/packaging#pep-517518-support-high-priority),
- [`pip` documentation](https://pip.pypa.io/en/stable/cli/pip/#pep-517-and-518-support).
The `setuptools>=42` requirement is adopted from the Scikit-HEP documentation, and likely aimed at `setuptools_scm` support. `40.8.0` may in principle be sufficient for `cabinetry` at the moment, but this implementation follows the Scikit-HEP recommendation anyway.
SDist / wheel building can be done with `pipx run build`.
Also adding `license_files` to metadata explicitly, which has defaulted to pick up the license correctly so far regardless (see [`setuptools` …
=> build: PEP 517/518 support

tests/test_integration.py
Slightly increases the tolerance for integration tests. This is required to make the tests pass with `iminuit` [2.8.0](https://iminuit.readthedocs.io/en/stable/changelog.html#july-25-2021), which updated the minimizer code to the `ROOT` master. The resulting change in fit results is negligible and has no physical impact.
=> test: increase integration test tolerance

src/cabinetry/fit.py, src/cabinetry/histo.py, src/cabinetry/visualize.py, tests/test_fit.py, tests/test_histo.py
Small improvements to string handling, including switches to f-strings in two more places. The formatting of p-values reported in significance calculations has been improved, now switching to scientific notation for small p-values.
```
* improved formatting of p-values reported in significance calculations
* small string handling improvements
```
=> refactor: small string handling improvements

src/cabinetry/__init__.py, src/cabinetry/cli/__init__.py, src/cabinetry/fit.py, src/cabinetry/route.py, src/cabinetry/template_builder.py, src/cabinetry/template_postprocessor.py, src/cabinetry/visualize/__init__.py, src/cabinetry/visualize/plot_model.py, src/cabinetry/visualize/plot_result.py, src/cabinetry/workspace.py
Motivated by https://github.com/scikit-hep/pyhf/pull/1539, this switches from relative to absolute imports within `cabinetry`. Reasons are outlined in https://github.com/scikit-hep/pyhf/pull/1539#issuecomment-895382525, reproduced below:
The [imports section of PEP 8](https://www.python.org/dev/peps/pep-0008/#imports) says
> Absolute imports are recommended, as they are usually more readable and tend to be better behaved (or at least give better error messages) if the import system is incorrectly configured
and
> However, explicit relative imports are an acceptable alternative to absolute imports, especially when dealing with complex package layouts where using absolute imports would be unnecessarily verbose
PEP 8 [used to discourage relative imports more …
=> refactor: use absolute imports

.github/workflows/dependencies-head.yml
The refactoring in #250 caused the nightly tests to fail. They previously skipped the figure comparison completely, but since that is now split across multiple files, some figures end up being left open and the test fails. This installs Ghostscript in the nightly tests to make them pass, and no longer skip figure comparisons.
```
* install Ghostscript in nightly tests for figure comparisons
```
=> test: install Ghostscript in nightly tests

src/cabinetry/schemas/config.json, src/cabinetry/template_builder.py, tests/test_template_builder.py
This adds support for overriding the histogram variable/observable in systematic templates. The `"Variable"` key in up/down templates (the nominal value is a required region property) is used for that, and any value specified overrides the nominal setting.
This can be useful if observables under systematic variations are saved in a branch with a different name (rather than just a different tree, but same branch name). It could also be used to simulate simplified systematic variations, for example by multiplying observables by a number (ignoring possible acceptance effects).
```
* support overriding histogram variable in systematic templates
```
=> feat: variable overrides in systematic templates

src/cabinetry/schemas/config.json
The JSON schema for config validation was missing the `Filter` and `RegionPath` settings for systematics templates, even though they were already supported within `cabinetry`. This adds the missing settings. `Filter` was supported since #65, but not added when the JSON schema was created in #69. `RegionPath` was added in #98 and fixed to work in #117, but not added to the schema for templates.
Also adds a check for systematics names to the schema, since `"Nominal"` is a reserved name with special handling inside `cabinetry`. This name is now caught as invalid by the schema validation.
```
* add missing Filter and RegionPath settings for systematic templates to config schema
* invalidate reserved systematics names in config schema
```
=> fix: add missing template settings to config schema

docs/advanced.rst, setup.cfg, src/cabinetry/schemas/config.json, src/cabinetry/workspace.py, tests/test_workspace.py
This adds a new optional setting `ModifierName` for systematics. If set, the name of affected modifiers in the workspace will be taken from this setting. By default the name is taken from the name of the systematic instead. This new setting enables manual correlation of systematics: modifiers with the same name in the workspace are correlated. This name set by `ModifierName` only enters the workspace (and subsequently shows up in inference results, which extract the name from the workspace). Everything in `cabinetry` leading up to workspace creation does not make use of the name, and instead uses the unique name of each systematic to identify it.
Added a section to the "advanced concepts" docs to explain the behavior.
resolves #213
```
* new systematics setting ModifierName to manually …
```
=> feat: manual correlation of systematics

src/cabinetry/route.py, src/cabinetry/visualize/__init__.py, tests/test_route.py, tests/visualize/test_visualize.py
The JSON schema for `cabinetry` configs does not require systematics, but so far the internal handling relied on them being present in the config, at least in form of an empty list. This fixes the behavior such that configs without systematics work as expected.
```
* fix handling of configs without systematics
```
=> fix: configs without systematics

src/cabinetry/configuration.py, tests/test_configuration.py
The names of regions/samples/systematics need to be unique, since they are used as keys within `cabinetry`. The names of normalization factors technically should not need to be unique, but there is no obvious gain by allowing non-unique names. This adds a check for uniqueness of all these names to `configuration.validate`, and raises `ValueError` if non-unique names are found.
Also updates the `configuration.validate` docstring, which had some outdated entries.
```
* validate uniqueness of region/sample/systematic/normfactor names in config
```
=> feat: validate uniqueness of names in config

docs/advanced.rst, setup.cfg, src/cabinetry/_typing.py, src/cabinetry/configuration.py, src/cabinetry/histo.py, src/cabinetry/route.py, src/cabinetry/schemas/config.json, src/cabinetry/template_builder.py, src/cabinetry/template_postprocessor.py, src/cabinetry/visualize/__init__.py, src/cabinetry/workspace.py, tests/test_configuration.py, tests/test_histo.py, tests/test_route.py, tests/test_template_builder.py, tests/test_template_postprocessor.py, tests/test_workspace.py, tests/visualize/test_visualize.py
The `cabinetry` internals previously used a placeholder for systematics via `{"Name": "Nominal"}` to indicate the nominal template being processed. This switches the treatment: "Nominal" is no longer treated as a reserved name (now possible to name systematics "Nominal" if desired), and the template choice is instead performed via the `template` arguments of functions. The two templates "Up" and "Down" are used throughout the code, and also referred to with the same name in the config. The "Nominal" template was previously used in some places, but this replaces this with `None` templates instead. If the template is `None`, that means the nominal setup is being considered.
The update requires slight changes in the custom template override API. Region/sample/systematic arguments can no …
=> refactor: improved nominal template handling

setup.cfg
Direct dependencies of `cabinetry` are now listed explicitly under `install_requires`. These dependencies are already provided via `pyhf`, and as such this change does not have an immediate effect. There are advantages to listing them explicitly anyway:
- in case `pyhf` decided to drop one of the dependencies, `cabinetry` would break, and this protects against that scenario,
- users can tell more easily which other libraries `cabinetry` makes direct use of,
- the dependency tree is more correct, as visualized e.g. by [`pipdeptree`](https://pypi.org/project/pipdeptree/).
The slightly more verbose `setup.cfg` seems like a negligible problem in comparison.
This partially reverts #168.
```
* explicitly require all direct dependencies of cabinetry via install_requires
```
=> build: list direct dependencies explicitly

src/cabinetry/histo.py, src/cabinetry/template_postprocessor.py, src/cabinetry/workspace.py, tests/test_histo.py, tests/test_template_postprocessor.py, tests/test_workspace.py
Histogram loading in the `workspace` module made (in a few cases) use of two functions `workspace.WorkspaceBuilder.get_yield_for_sample` and `workspace.WorkspaceBuilder.get_unc_for_sample`. These functions were thin wrappers around `histo.Histogram.from_config`, and did not properly support loading histograms for systematic variations. Following the refactoring in #260, these functions are now dropped in favor of using `histo.Histogram.from_config` directly. They did not offer sufficient extra convenience to justify their existence, and loading yields / uncertainties separately was inefficient.
The `histo.Histogram.from_config` interface changes very slightly: the keyword arguments `template` and `modified` switch places.
**Breaking changes:**
- removed …
=> refactor: streamline histogram loading

src/cabinetry/model_utils.py, tests/test_model_utils.py
The calculation of yield uncertainties can be slow. This adds a caching mechanism to `model_utils.yield_stdev` to avoid re-calculating the results if nothing has changed. Addresses a part of #251.
```
* added caching to yield uncertainty calculation in model_utils.yield_stdev
```
=> feat: yield uncertainty caching

src/cabinetry/visualize/__init__.py, tests/visualize/test_visualize.py
#264 caused figures to be returned from `visualize` functions. When used in a notebook with `matplotlib` inline backend, figures produced by functions returning a single figure were then rendered twice: once because they are still open, and once because they are the return value of the last line in the cell. This changes the default setting for functions returning a single figure (`correlation_matrix`, `pulls`, `ranking`, `scan`, `limit`) to `close_figure=True`. A cell such as
```python
cabinetry.visualize.pulls(...)
```
then will only show the produced figure once (because it is the return value of the last line in the cell). The same behavior can be achieved in other ways, see https://github.com/alexander-held/cabinetry/issues/265#issuecomment-907621136 for more details.
Multi-figure …
=> feat: close single figures by default

setup.py, src/cabinetry/cli/__init__.py, src/cabinetry/contrib/histogram_creation.py, src/cabinetry/fit/__init__.py, src/cabinetry/histo.py, src/cabinetry/route.py, src/cabinetry/tabulate.py, src/cabinetry/visualize/__init__.py, src/cabinetry/visualize/plot_model.py, src/cabinetry/visualize/plot_result.py, src/cabinetry/workspace.py, tests/cli/test_cli.py, tests/conftest.py, tests/fit/test_fit.py, tests/test_configuration.py, tests/test_model_utils.py, tests/test_tabulate.py, tests/test_workspace.py, tests/visualize/test_plot_model.py, tests/visualize/test_visualize.py
This applies changes from `black` that are introduced by `--experimental-string-processing` (which will eventually become the default), as long as running `black` again without that flag does not revert the changes. It also applies changes from [`--skip-magic-trailing-comma`](https://black.readthedocs.io/en/latest/the_black_code_style/current_style.html#the-magic-trailing-comma), again as long as those changes are not reverted by running `black` without that flag. Magic commas have not been used purposefully for formatting in the codebase so far, so the changes due to this should be coming mostly from code that was too long for a single line, later on made shorter such that it once again fits into a single line, but was not formatted again due to a trailing comma.
```
* apply selected …
```
=> style: apply optional formatting to magic commas and strings

tests/cli/test_cli.py, tests/test_template_builder.py
This is a minor follow-up to #269, introducing a bit more harmonization. `call_args` is used instead of `call_args_list[-1]` depending on the context, and `call_count` is used instead of the `call_args_list` length.
```
* further harmonized formatting of expected call arguments for mocked objects in tests
```
=> test: additional call argument formatting harmonization

.pre-commit-config.yaml, src/cabinetry/contrib/histogram_creation.py, src/cabinetry/fit/results_containers.py, src/cabinetry/histo.py, src/cabinetry/model_utils.py, src/cabinetry/template_builder.py, src/cabinetry/visualize/plot_model.py, src/cabinetry/workspace.py
This adopts `np.ndarray` in docstrings, where in some cases previously `numpy.ndarray` was used. The type of `cabinetry.fit.results_containers.LimitResults.observed_limit` was wrong in the docstring, this is also fixed. A few issues flagged by `pydocstyle` (via `pydocstyle --convention google src/cabinetry/`) are also fixed, and `pre-commit` is updated.
```
* harmonized use of np.ndarray in docstrings
* fixed type of LimitResults.observed_limit in docstring
* multiple minor docstring formatting fixes
* pre-commit updated
```
=> docs: multiple minor docstring fixes

.github/workflows/CI.yml, setup.cfg, setup.py, src/cabinetry/fit/__init__.py, src/cabinetry/model_utils.py, tests/fit/test_fit.py, tests/test_backends.py, tests/test_integration.py, tests/test_model_utils.py, tests/visualize/test_visualize.py
https://github.com/scikit-hep/pyhf/pull/1536 (see also discussion in https://github.com/scikit-hep/pyhf/issues/867) added `model.config.par_names()` to the `pyhf` model config API. This provides the same functionality as `cabinetry.model_utils.parameter_names`, but the parameter names are now also passed through to MINUIT. A fix is included to pass the correct names when using MINOS (they used to be `x0`, `x1` etc.). `cabinetry.model_utils.parameter_names` is removed, since the functionality is now available directly in `pyhf`.
The parameter naming format has changed: `parameter[bin_0]` -> `parameter[0]` etc., and the index is now included even for parameters like shapesys/shapefactors that only have a single component (because there is only a single bin in the region, see …
=> fix: compatibility with pyhf 0.6.3 (parameter label API, auxdata)

.github/workflows/CI.yml, .github/workflows/dependencies-head.yml, .pre-commit-config.yaml, .readthedocs.yml, setup.cfg
`pyhf` added Python 3.9 support via https://github.com/scikit-hep/pyhf/pull/1574, which is now available as of `pyhf` v0.6.3. This means that also `cabinetry` can officially support Python 3.9 (the only blocker for this was `pyhf`). Tests are added for Python 3.9, and others are updated where sensible.
resolves #275
```
* add Python 3.9 support and test Python 3.9 in CI
```
=> feat: add Python 3.9 support

.github/workflows/test-package.yml, MANIFEST.in
Add a `MANIFEST.in` to the project that initially adds nothing (prunes everything), then adds only the files in `src` and `tests`, and then adds all ["default" files for a `sdist` in `MANIFEST.in`](https://packaging.python.org/guides/using-manifest-in/#how-files-are-included-in-an-sdist). Additionally add a GHA based workflow to test building a package using `build` that also checks the package manifest and will list the contents of the resulting `sdist` and `wheel` for visual checks of the CI logs.
For additional context c.f. https://github.com/scikit-hep/pyhf/pull/1449
**Suggested squash and merge commit message**
```
* Add a MANIFEST.in to tell packagers what to include when building a package
* Use `prune **` to remove all files from the sdist
- c.f. …
```
=> feat: Add `MANIFEST.in`

setup.cfg, src/cabinetry/__init__.py
Updating to version 0.3.0. `cabinetry` now returns figure objects for further customization, and multiple breaking API changes have been introduced. The minimum required `pyhf` version is now 0.6.3, and Python 3.9 is officially supported.
```
* updating version to 0.3.0
```
=> chore: updating version to 0.3.0

.github/workflows/CI.yml, .github/workflows/dependencies-head.yml
CI started failing during `ghostscript` installation. This is caused by the package list being slightly outdated and fixed by updating it via `apt-get update` before installing `ghostscript`. Thanks a lot to @matthewfeickert for the debugging help!
```
* update package list to fix failing ghostscript installation in CI
```
=> ci: update package list

.pre-commit-config.yaml, src/cabinetry/contrib/histogram_creation.py, src/cabinetry/template_builder.py, tests/contrib/test_histogram_creation.py, tests/test_template_builder.py
The `uproot`-based backend for ntuple reading and histogram creation previously used `boost-histogram` to bin data, then subsequently extracted yields and uncertainties and returned those in a tuple to `cabinetry.template_builder`, where they would again be turned into a (`cabinetry`) histogram and saved. This changes the interface such that `cabinetry.contrib.histogram_creation.from_uproot` returns a `boost-histogram` histogram, which then gets wrapped by a `cabinetry` histogram and saved. The conversion to a tuple of yields/uncertainties is skipped, as it was unnecessary. Returning a histogram instead of a tuple also brings this in line with the format of user-provided and `register_template_builder`-decorated functions that have to also return `boost-histogram` histograms.
Also updates …
=> feat: return histogram instead of tuple from histogram creation backend

CONTRIBUTING.md, README.md, docs/config.rst, docs/index.rst, setup.cfg, src/cabinetry/schemas/config.json
`cabinetry` has joined Scikit-HEP, and migrated from `alexander-held/cabinetry` to `scikit-hep/cabinetry`. This updates all links to point to the new repository, and adds a Scikit-HEP badge to the readme.
```
* updated links to point to new repository location scikit-hep/cabinetry
* added Scikit-HEP badge to readme
```
=> chore: update links after Scikit-HEP migration

src/cabinetry/schemas/config.json
Event filtering is not strictly required for model building, and as such should be optional. This changes the config schema to make the `Filter` property of regions optional to achieve this. The code already handles this scenario correctly, with a `None` filter passed through in this case.
```
* updated config schema to make the Filter property of regions optional
```
=> feat: make Filter property of regions optional

src/cabinetry/visualize/plot_model.py, tests/visualize/test_plot_model.py
An infinite entry in a `matplotlib` bar plot seems to make all bars disappear when the `bottom` kwarg is used:
```python
import matplotlib.pyplot as plt
import numpy as np
unc = np.asarray([np.inf, 0.2])
plt.bar([1,2], 2*unc, bottom = 1-unc)
```
The plot works when replacing `np.inf` by some number, and without the `bottom` kwarg only the second bar is drawn (even with `np.inf` in the first entry of the array).
This behavior causes the MC uncertainty band in data/MC ratio panels to disappear if the model prediction in any bin is zero. To fix this, the ratio panel will now only be populated for bins where the model prediction is non-zero. In the remaining panels the content is ill-defined. This also adds a warning if the prediction in any bin is zero.
Thanks @Daniel-Noel for reporting …
=> fix: ratio panel in data/MC plots for bins with zero predicted yields

src/cabinetry/schemas/config.json, src/cabinetry/template_builder.py, tests/test_template_builder.py
This adds an optional `Filter` property to samples. If a filter is specified at the sample level, it overrides the (optional) filter defined at the region level. Filter overrides could already previously exist at the systematic level, and these override the sample-level filter setting. In increasing order of priority, the filter used is specified at region -> sample -> systematic level.
```
* added optional Filter property to samples in config schema
* sample-level filters override region-level settings, and are overridden by systematics-level filters
```
=> feat: sample-specific Filter overrides

.pre-commit-config.yaml, README.md, src/cabinetry/model_utils.py, tests/test_model_utils.py
This adds a new API `model_utils.match_fit_results`, which takes a model and a fit result and then returns a modified fit result that matches the model as well as possible:
- re-ordering parameters if needed,
- removing parameters from fit result that are not in the target model,
- adding parameters that are in the model but not in the fit result.
When adding new parameters to the fit result, they are assumed to have their pre-fit values as given by `model_utils.asimov_parameters`, with associated uncertainty given by `model_utils.prefit_uncertainties`. They are furthermore assumed to not have any correlations with other parameters.
Additional minor changes:
- pre-commit updated
- changed `np.diag` (MATLAB-like API) to `np.diagflat`
- minor capitalization changes in readme
- added warning …
=> feat: utility to match fit results to arbitrary model

src/cabinetry/schemas/config.json
This updates the config schema to make `RegionPath` and `SamplePath` optional for histogram inputs. #289 already introduced all the logic required to handle that scenario, but made the schema restrictive and required both these settings. While `SamplePath` is likely needed for most/all setups, `RegionPath` is not needed for single-distribution fits.
```
* made RegionPath and SamplePath settings optional for histogram inputs
```
=> feat: region- and sample-specific paths are optional for histogram inputs

.pre-commit-config.yaml, setup.cfg, src/cabinetry/__init__.py, src/cabinetry/cli/__init__.py, src/cabinetry/configuration.py, src/cabinetry/fit/results_containers.py, src/cabinetry/smooth.py, src/cabinetry/templates/utils.py, src/cabinetry/visualize/utils.py
This adds `pydocstyle` to `pre-commit` and adds the last module-level docstrings that were still missing.
```
* added pydocstyle to pre-commit
* added remaining missing module-level docstrings
```
=> feat: add pydocstyle to pre-commit and add missing docstrings

.pre-commit-config.yaml, src/cabinetry/visualize/__init__.py, tests/test_model_utils.py, tests/test_route.py, utils/create_ntuples.py
Adding [`codespell`](https://github.com/codespell-project/codespell/), a spell-checker for code, to `pre-commit` so it runs automatically (including via CI). The tool flagged a few typos, which have been fixed.
```
* added codespell to pre-commit
* fixed spelling mistakes flagged by codespell
```
=> feat: add codespell to pre-commit and fix typos

MANIFEST.in
Updating `MANIFEST.in` to exclude `*.root` files from source distributions. Such files are for example produced from the ntuple / histogram creation scripts in `utils/`.
```
* excluded .root files from source distribution
```
=> build: exclude root files from source distribution

setup.py
`uproot` [4.1.4](https://github.com/scikit-hep/uproot4/releases/tag/4.1.4) added `TStreamerInfo` for `TTrees` written to files. This ensures that they can be read by older versions of ROOT as well. While this is not strictly needed for the purposes of `cabinetry` at the moment (ROOT file writing is only used to produce example inputs for demonstration purposes), it nevertheless seems good to update to this latest version. This will avoid possible complications when trying to open the files produced by `uproot` in another ROOT version (an older version, or possibly even a newer version in the future).
```
* updated uproot version to 4.1.4 to ensure trees are readable by old ROOT versions
```
=> fix: update uproot version to ensure trees are readable by old ROOT versions

.github/workflows/dependencies-head.yml
Use of the unauthenticated git protocol (`git://`) is no longer supported on GitHub (c.f. the 2021-09-01 GitHub Security blog [Improving Git protocol security on GitHub](https://github.blog/2021-09-01-improving-git-protocol-security-github/)). As a result, the [current HEAD of dependencies workflow](https://github.com/scikit-hep/cabinetry/blob/b89bb09b97608e984864cde6d45f9b8901612a06/.github/workflows/dependencies-head.yml) fails with an error similar to that seen in https://github.com/scikit-hep/pyhf/pull/1680. 
e.g.
```
Collecting git+git://github.com/scikit-hep/uproot4.git
Cloning git://github.com/scikit-hep/uproot4.git to /tmp/pip-req-build-6mgjtjoo
Running command git clone --filter=blob:none -q git://github.com/scikit-hep/uproot4.git /tmp/pip-req-build-6mgjtjoo
fatal: remote error: …
```
=> fix: Use https protocol over unauthenticated git protocol

.pre-commit-config.yaml, src/cabinetry/model_utils.py, tests/test_model_utils.py
This drops `model_utils._channel_boundary_indices` and instead adopts the `pyhf` API to allow splitting yields by channel with `model.config.channel_slices`. See also https://github.com/scikit-hep/pyhf/issues/1141.
```
* adopted pyhf API to split yields by channel with model.config.channel_slices
* removed model_utils._channel_boundary_indices
```
=> refactor: use pyhf API to split yields by channel

.pre-commit-config.yaml, src/cabinetry/fit/__init__.py, src/cabinetry/fit/results_containers.py, tests/fit/test_fit.py, tests/fit/test_fit_results_containers.py
This adds the lower/upper parameter uncertainties calculated with MINOS to the fit results container returned by MLE fits, in a new property called `minos_uncertainty`. While the symmetric uncertainties (calculated via the Hessian) are a list, the MINOS uncertainties are provided in a dict. This change in pattern is in line with how the MINOS uncertainties are calculated, requiring the parameter name(s) of the parameter(s) for which the algorithm is run in `fit.fit` (via the `minos` kwarg). If MINOS is not run, the dict is empty.
For the sake of keeping the results containers minimal and streamlined, a simple dict is used (as opposed to something like a `defaultdict`).
```
* MINOS parameter uncertainties are returned from fits via minos_uncertainty dict in FitResults container
* updated …
```
=> feat: include MINOS uncertainties in fit results container

src/cabinetry/visualize/plot_result.py
The axis limit calculation for the impact axis in ranking plots only took impacts in up direction into account so far, accidentally overriding the array containing impacts in down direction instead of considering them too. Since the impacts had already been plotted when this happened, it does not affect the plotted values but only the axis limits. This fixes the bug and considers impacts in both up and down direction.
```
* take impacts in both up and down direction into account for the impact axis limits in ranking plots
```
resolves #308
=> fix: ranking plot axis limits for impacts

.pre-commit-config.yaml, src/cabinetry/model_utils.py, tests/test_model_utils.py
#303 introduced a bug in `model_utils.prediction` when used with multi-channel models. The split of yields into channels was happening at the wrong depth after this refactor. This update fixes the bug, and changes the corresponding test to catch such an issue.
```
* fixed channel splitting for multi-channel model predictions
```
=> fix: channel splitting for multi-channel model predictions

docs/index.rst
The link now points to the published version of the proceedings.
```
* updated vCHEP 2021 proceedings link to point to the published paper
```
=> docs: update link to vCHEP 2021 proceedings

src/cabinetry/cli/__init__.py, src/cabinetry/fit/__init__.py, src/cabinetry/fit/results_containers.py, src/cabinetry/visualize/__init__.py, src/cabinetry/visualize/plot_result.py, tests/cli/test_cli.py, tests/fit/test_fit.py, tests/fit/test_fit_results_containers.py, tests/visualize/test_visualize.py, tests/visualize/test_visualize_plot_result.py
The confidence level for upper parameter limit determination was previously hardcoded to 95%. It is now customizable in `fit.limit` via a new `confidence_level` keyword argument, and in the `cabinetry limit` CLI via `--cl` or `--confidence_level`. The confidence level is added to the `LimitResults` container, and the visualization via `visualize.limit` uses the value from the container when drawing the horizontal line visualizing the target CLs value.
```
* added confidence_level keyword argument to fit.limit to configure desired confidence level
* LimitResults container now contains confidence level in confidence_level property
* added configurable confidence level to command-line interface for parameter limits
```
=> feat: customizable confidence level for upper parameter limits

.pre-commit-config.yaml, src/cabinetry/histo.py, src/cabinetry/model_utils.py, tests/conftest.py, tests/templates/test_templates_builder.py, tests/test_integration.py, tests/test_route.py, utils/create_histograms.py
The [first non-beta release of `black`, `22.1.0`](https://black.readthedocs.io/en/stable/change_log.html) introduced some small formatting changes. This updates the code to the latest version of `black`.
```
* apply formatting changes introduced by black 22.1.0
```
=> style: apply black 22.1 formatting

tests/test_integration.py
Slightly relax the tolerance for yield uncertainty in an integration test. The previous default was slightly larger than the differences between two local setups. The new absolute tolerance is much smaller than what would usually be a physically significant difference.
```
* slightly relax tolerance in comparison of yield uncertainties in integration test
```
=> test: relax yield uncertainty tolerance in integration test

tests/conftest.py
When tests fail, the captured log calls sometimes contain a lot of `DEBUG` level output from `matplotlib.font_manager`. This modifies the logging configuration in tests such that the minimum level for `matplotlib` log output is now `INFO`. The implementation is adopted from https://stackoverflow.com/a/66925665.
```
* set log level of matplotlib in tests to INFO
```
=> test: increase log level for matplotlib in tests

src/cabinetry/fit/__init__.py, tests/fit/test_fit.py
This adds customization to maximum likelihood fits via `fit.fit`:
- initial parameter values via `init_pars`,
- setting parameters to constant via `fix_pars`,
- parameter bounds via `par_bounds`.
The names of the kwargs generally follow the `pyhf` naming, however `fix_pars` currently differs from the currently used `fixed_params` used in `pyhf` (https://github.com/scikit-hep/pyhf/issues/1757). A harmonization in `pyhf` should probably be propagated to `cabinetry` as well in case it happens.
This change revealed a small type inconsistency in `pyhf`-provided default parameter bounds, which is being followed up in https://github.com/scikit-hep/pyhf/issues/1755.
```
* added parameter customization options to fit.fit API
* new supported keyword arguments are init_pars, fix_pars, and par_bounds …
```
=> feat: parameter customization for maximum likelihood fits

setup.cfg, src/cabinetry/fit/__init__.py, tests/fit/test_fit.py
This is an extension of #320, adding `init_pars` / `fix_pars` / `par_bounds` also to the remaining `fit` API: `fit.ranking`, 
`fit.scan`, `fit.limit`, `fit.significance`.
Small improvement added: set lower POI bound for limit to `0.0` only if existing bound is smaller than 0.
```
* added parameter customization options to remaining fit API
* supported keyword arguments are the same as for fit.fit: init_pars, fix_pars, and par_bounds
* set lower POI bound for limit to 0 only if default is below zero
```
=> feat: parameter customization for general inference

src/cabinetry/model_utils.py, tests/test_model_utils.py
This implements the changes to hashing discussed in [#315](https://github.com/scikit-hep/cabinetry/issues/315#issuecomment-1023583140).
It was necessary to modify one test that was directly looking up cached results in the `yield_stdev` cache.
```
* caching for yield uncertainty calculation now based on model specification and interpolation codes
* caching now works when re-creating pyhf.pdf.Model objects
```
=> perf: cache yield_stdev using spec and interpcodes of model

src/cabinetry/model_utils.py, tests/test_integration.py, tests/test_model_utils.py
The `model_utils.yield_stdev` implementation contained an optimization for `staterror`-`staterror` cross terms, which have no contribution when calculating per-bin uncertainties:
https://github.com/scikit-hep/cabinetry/blob/f34c73acec8d80e012ff0a4abbf44b29204af888/src/cabinetry/model_utils.py#L303-L307
When the functionality to calculate per-channel uncertainties was added in #189, the optimization should have been updated, since these cross terms no longer cancel out for the per-channel calculation. This now fixes the bug in per-channel yield uncertainties by removing this performance optimization completely.
While this does make the calculation slower overall, that is not a concern since it will be replaced completely by #316 afterwards, resulting in a significant speed-up. This …
=> fix: per-channel yield uncertainty contribution from staterror-staterror terms

src/cabinetry/model_utils.py
This vectorizes the previously loop-based calculations when determining yield uncertainties. Thanks a lot to @agoose77 for the invaluable help!
For a moderately complex workspace with roughly 20 samples in 50 bins and 200 (non-expanded) parameters, the runtime of the diagonal contributions goes from 0.7 s to below 0.01 s (including setting up an array that is re-used for off-diagonal terms). The off-diagonal contribution goes from 180 s to 0.4 s.
After these changes, the bottleneck in `yield_stdev` is now the initial setup of the yields for all variations (4 s in the above example). There is probably some room to optimize this a bit further as well (example in https://github.com/scikit-hep/cabinetry/issues/315#issuecomment-1033705658). This topic will be tracked in #325.
The vectorization …
=> perf: vectorize yield uncertainty calculation

src/cabinetry/model_utils.py, tests/test_model_utils.py
This adds a dedicated unit test for the model key `model_utils. _hashable_model_key` introduced in #322, which was previously tested only via the `model_utils.yield_stdev` test.
```
* added dedicated unit test for model keys
```
=> test: dedicated test for model keys

setup.cfg, src/cabinetry/__init__.py
Updating to version `0.4.1`. This new version brings a few new features for the `cabinetry.fit` API, fixes contributions from `staterror` modifiers in the post-fit yield uncertainty calculation, and significantly speeds up the calculation of yield uncertainties.
```
* updating version to 0.4.1
```
=> chore: updating version to 0.4.1

pyproject.toml
As pointed out by @henryiii (thanks!), `wheel` is not required in the list of `build-system` requirements according to [PEP 517](https://www.python.org/dev/peps/pep-0517/). See https://github.com/scikit-hep/pylhe/pull/111 and https://github.com/scikit-hep/pyhf/pull/1788.
```
* remove superfluous wheel requirement in build-system
```
=> build: remove wheel from build-system requirements

.github/workflows/CI.yml, .github/workflows/dependencies-head.yml, .github/workflows/test-package.yml, .pre-commit-config.yaml
Updating versions of GitHub actions:
- [`checkout`](https://github.com/actions/checkout) is available as v3: https://github.com/actions/checkout/releases/tag/v3.0.0 
- [`setup-python`](https://github.com/actions/setup-python/) is available as v3: https://github.com/actions/setup-python/releases/tag/v3.0.0
- [`codecov`](https://github.com/codecov/codecov-action) is available as v2.1: https://github.com/codecov/codecov-action/releases/tag/v2.1.0
The previously used v1 of the Codecov action has been sunset since Feb 1, 2022 according to the [README](https://github.com/codecov/codecov-action/blob/b049ab51f46ef6cd9c7ca52a856631a818969c7c/README.md#%EF%B8%8F--deprecration-of-v1), but still seems to have worked up to now in this repository.
```
* updated versions of GitHub actions: checkout, …
```
=> ci: update GitHub actions

.github/workflows/CI.yml, .github/workflows/dependencies-head.yml, .github/workflows/test-package.yml, .pre-commit-config.yaml
Updating GitHub actions:
- `setup-python` v4: https://github.com/actions/setup-python/releases/tag/v4.0.0
- `pre-commit` v3: https://github.com/pre-commit/action/releases/tag/v3.0.0
- `codecov` v3: https://github.com/codecov/codecov-action/releases/tag/v3.1.0
Also including a pre-commit update.
```
* updated versions of GitHub actions: setup-python v4, pre-commit v3, codecov v3
* use strings for Python versions in CI
```
=> ci: update versions of GitHub actions and pre-commit

src/cabinetry/fit/__init__.py
Starting from `iminuit` version v2.12.1, running MIGRAD will set non-zero step sizes for all parameters (including fixed parameters) and does no longer just carry through the value of `0.0` that `cabinetry` sets for them before minimization. See https://github.com/scikit-hep/iminuit/issues/762 for details. To keep post-fit parameter uncertainties for fixed parameters at zero, this now sets the relevant values to `0.0` after minimization. As there is no longer any benefit to setting the value to zero before the fit, the initial step size settings are removed.
```
* explicitly set post-fit parameter errors to 0 for fixed parameters for compatibility with iminuit>=2.12.1
```
=> feat: explicitly set post-fit parameter errors to 0 for fixed parameters

README.md
With `cabinetry` now available through conda-forge (thank you @oshadura!), it makes sense to have the corresponding readme badge.
```
* add conda-forge badge to readme
```
=> docs: add conda-forge badge

.github/workflows/CI.yml, .github/workflows/dependencies-head.yml, .github/workflows/test-package.yml, .pre-commit-config.yaml, setup.cfg
Since `pyhf` now supports 3.10 (https://github.com/scikit-hep/pyhf/pull/1808, https://github.com/scikit-hep/pyhf/pull/1809), `cabinetry` should also officially support it. This adds the relevant metadata and adds Python 3.10 to the CI. See #277 for the corresponding PR that added Python 3.9 support.
This should only be merged after https://github.com/scikit-hep/cabinetry/pull/301, which adds support for the upcoming `pyhf` 0.7 release.
```
* add Python 3.10 support and test Python 3.10 in CI
```
=> feat: add Python 3.10 support

setup.cfg, src/cabinetry/fit/__init__.py, src/cabinetry/model_utils.py, src/cabinetry/schemas/config.json, src/cabinetry/workspace.py, tests/fit/test_fit.py, tests/test_configuration.py, tests/test_model_utils.py, tests/test_workspace.py, tests/visualize/test_visualize_plot_model.py
The changes in https://github.com/scikit-hep/pyhf/pull/1638 and https://github.com/scikit-hep/pyhf/pull/1636 made POIs in `pyhf` workspaces optional. This means they can also be optional for the `cabinetry` config when building models. If not specified, the POI defaults to `""` which is interpreted as "no POI" by `pyhf`.
A new keyword argument `poi_name` was added to `fit.ranking` and `fit.limit` to override the POI given in the model config.
Also fixing a deprecation warning observed in a test.
resolves #347
```
* POI is now an optional configuration argument
* added ability to set POI via poi_name keyword arguments in fit.ranking and fit.limit
* fixed pytest deprecation warning in a test
```
=> feat: make POI optional in config and allow POI customization for inference

.github/workflows/dependencies-head.yml, src/cabinetry/contrib/histogram_creator.py
The tests of the most recent versions of dependencies started failing for `uproot5`. The reason is that `uproot5` uses the `awkward` v2 API, but the histogram creation code in `cabinetry` uses `awkward` directly as well (which currently results in v1). The two do not mix:
```python
import awkward as ak
a = ak._v2.Array([1,2,3])
ak.to_numpy(a)
```
results in
```pytb
TypeError: unrecognized array type: <Array [1, 2, 3] type='3 * int64'>
```
The solution is to call `.to_numpy()` on the relevant arrays instead, which will then use the v2 API in these tests. As `uproot5` and `awkward` v2 should release at the same time, this probably would not have an impact on users, but this change should keep the tests working.
```
* fix test of upcoming versions of uproot5
```
=> fix: avoid mixing different versions of awkward in uproot5 tests

src/cabinetry/cli/__init__.py, tests/cli/test_cli.py
The CLI did not support `cabinetry --version` so far, so this is added here via built-in `click` functionality.
```
* add support for cabinetry --version to the command line interface
```
=> feat: add version to command line interface

.pre-commit-config.yaml, src/cabinetry/tabulate.py, tests/test_tabulate.py
Return dict with yield tables from `tabulate.yields` (this previously returned `None`).
This can be argued to be a breaking change; while it seems unlikely that anyone is relying on the return value of `None`, marking this as "breaking" to be safe.
```
* breaking change: return dict with yield tables from tabulate.yields
```
=> feat: return yield tables

.gitignore, src/cabinetry/tabulate.py, tests/test_tabulate.py
Automatically save yield tables when they are produced. The destination and format are customizable and controlled by new `tabulate.yields` keyword arguments: `table_folder` and `table_format`. The format can be any of the formats supported by the `tabulate` library, see https://github.com/astanin/python-tabulate#table-format. The automatic saving of tables can be turned off via `save_tables`.
```
* support automatic saving of yield tables in customizable formats
```
=> feat: save yield tables

src/cabinetry/fit/__init__.py, tests/fit/test_fit.py, tests/test_integration.py
Adding minimizer configuration options to `cabinetry.fit`: `strategy`, `maxiter` and `tolerance` allow configuring the Minuit strategy, maximum number of iterations and tolerance for Migrad. This extends the `fit` API functionality, similarly to #320 and #321.
When fitting with `custom_fit=True`, a `ValueError` is now raised if the fit fails.
Since the `pyhf` fit API does not support `strategy=None` currently (see https://github.com/scikit-hep/pyhf/issues/1785), the strategy kwarg is only propagated for values other than `None`. This can be refactored in the future in case this changes.
The integration test changes are due to the default tolerance with `custom_fit=True` now matching the default when using the `pyhf` fit API (previously the tolerance was reduced by a factor of ten). …
=> feat: minimizer configuration for fit.fit

.pre-commit-config.yaml
#333 changed the pre-commit config, adding additional dependencies to the `mypy` stage. Those were needed to make things run locally, but they do not seem to be needed anymore in a clean environment (nor were they required previously). Removing them again as things seem to run fine without them.
```
* remove unnecessary dependencies for mypy running in pre-commit
```
=> fix: remove unnecessary dependencies for mypy

pyproject.toml, src/cabinetry/histo.py
Adding suggested `mypy` flags from https://scikit-hep.org/developer/style#type-checking.
```
* add suggested mypy flags from the Scikit-HEP developer pages
```
=> feat: add suggested optional mypy checks

.pre-commit-config.yaml, pyproject.toml, setup.cfg, src/cabinetry/model_utils.py, src/cabinetry/tabulate.py, src/cabinetry/visualize/__init__.py, tests/test_integration.py, tests/test_model_utils.py, tests/test_tabulate.py, tests/visualize/test_visualize.py
Adds per-sample yield uncertainty calculations and the propagation to yield tables.
The per-sample calculation is not implemented as an optional choice, but always performed. With everything already vectorized, the calculation is still fast with reasonably large models. If this becomes a bottleneck, it may make sense to allow making the per-sample calculation optional.
resolves #191
resolves #326 by switching to `awkward._v2` for the summation where this matters
**breaking changes**:
- `model_utils.ModelPrediction` changed: new sample dimension for `total_stdev_model_bins`  / `total_stdev_model_channels`
- `model_utils.yield_stdev` returns this new version of `ModelPrediction`
```
* breaking change: model_utils.ModelPrediction uncertainty structure now supports per-sample uncertainties
* …
```
=> feat: yield uncertainties per sample

README.md, example.py, tests/test_integration.py
Instead of storing the output of `model_utils.prediction` in variables named `model_*`, this PR switches to `prediction_*`. The use of `model` in the name could be misleading as the statistical model (`pyhf.pdf.Model`) is also called "model", and the model prediction is a different object.
```
* use "prediction" instead of "model" for model_utils.prediction return value names in examples
```
=> feat: rename model prediction variable in examples

src/cabinetry/fit/__init__.py, tests/fit/test_fit.py, tests/test_integration.py
When performing fits via the `fit` API (e.g. MLEs or `pyhf.infer.hypotest` via `fit.limit` / `fit.significance`), the optimizer is set to Minuit by `cabinetry` via `pyhf.set_backend`. Previously it just stayed this way, but now it instead gets set back to the initial settings (e.g. back to `scipy`, which is the `pyhf` default).
Now that the second RC for `pyhf` 0.7.0 is out, the integration test tolerance has to be slightly relaxed for CI to pass. Unclear why #361 is not affected by this. Locally a change in result bisects to https://github.com/scikit-hep/pyhf/pull/1919, but the difference is so small that it likely is down to floating point differences amplifying in the post-fit yield uncertainty calculation.
```
* restore original pyhf optimizer settings after fits (for which Minuit is …
```
=> feat: restore optimizer settings after fits

src/cabinetry/schemas/config.json, src/cabinetry/workspace.py, tests/test_workspace.py
Added a new config option `DisableStaterror` for samples. It defaults to false, and can be set to true in order to skip the creation of automatic `staterror` modifiers for the respective sample during workspace building.
resolves #276
```
* added sample configuration option "DisableStaterror" to disable automatic creation of staterror modifiers
```
=> feat: support disabling staterror per sample in workspace creation

setup.cfg
`v0.7.0rc2` fixes a regression in `staterror` introduced after `v0.6.3` and so is present in `v0.7.0rc1`.
=> build: Update lower bound of pyhf to v0.7.0rc2

src/cabinetry/fit/__init__.py, tests/fit/test_fit.py
As an extension of #330, this propagates `strategy` / `maxiter` / `tolerance` to the remaining fit API: `fit.ranking`,
`fit.scan`, `fit.limit`, `fit.significance`.
Both `limit` and `significance` use `pyhf.infer.hypotest`, which does not support passing in these settings as keyword arguments. Instead they are passed in via the minimizer configuration in the `pyhf.set_backend` call.
**breaking change:**
- renamed the former `fit.limit` keyword arguments `tolerance` and `maxiter` to `poi_tolerance` and `maxsteps` to avoid clashes with the minimizer configuration
resolves #329
```
* added minimizer configuration options to remaining fit API
* supported keyword arguments are the same as for fit.fit: strategy, maxiter and tolerance
* breaking change: fit.limit keyword arguments tolerance and …
```
=> feat: minimizer configuration for general inference

.pre-commit-config.yaml, src/cabinetry/model_utils.py, tests/test_model_utils.py
Extending the `model_utils.asimov_data` API to allow feeding in a `FitResults` object to create post-fit Asimov datasets (with auxiliary data set to the best-fit values, such that subsequent fits to that dataset reproduce the best-fit values used to create the dataset). New `poi_name` and `poi_value` keyword arguments allow setting a POI to a specific value.
```
* model_utils.asimov_data supports post-fit Asimov dataset generation via new keyword argument fit_results
* added support for custom POI values in Asimov dataset generation
```
=> feat: post-fit Asimov data generation

.github/workflows/CI.yml, setup.cfg, src/cabinetry/fit/__init__.py
#348 added the possibility to specify a custom POI via a kwarg in `fit.limit`. This was done by setting `model.config.poi_name` and `model.config.poi_index` directly, which is no longer possible after https://github.com/scikit-hep/pyhf/pull/1972 (see https://github.com/scikit-hep/pyhf/issues/1984). https://github.com/scikit-hep/pyhf/pull/1985 adds support for `None` POI values in `model.config.set_poi`, which allows that API to be used instead. This PR switches to this dedicated API to support temporarily changing the POI, which requires an update of the minimum `pyhf` version to `0.7.0rc4`.
```
* use pyhf model.config.set_poi API to support temporary POI changes in limit calculations
```
=> fix: set POI for limit calculations via dedicated pyhf API

src/cabinetry/fit/__init__.py, tests/fit/test_fit.py
This is an extension of #348 to also support `poi_name` in `fit.significance`. This allows to specify the parameter for which the significance calculation is performed.
The implementation follows #364, and as such also requires at least the `pyhf` RC 4 for v0.7 that was added there.
```
* added ability to set POI via poi_name keyword argument in fit.significance
```
=> feat: customizable POI for significance

setup.cfg, src/cabinetry/fit/__init__.py, src/cabinetry/model_utils.py, tests/test_model_utils.py
Following the release of `pyhf` `v0.7.0`, update to the latest API and update the lower bounds.
```
* Update lower bound of pyhf to v0.7.0
* Update all usage of `.par_names()` to `par_names`
```
=> build: Update lower bound of pyhf to v0.7.0

setup.cfg
The figure layout refactor introduced in `cabinetry` 0.5.0 requires `matplotlib` 3.5.0 or newer. Raise the minimum required version accordingly to prevent crashes with older versions.
resolves #369
```
* raise minimum required matplotlib version to 3.5.0
```
=> build: raise minimum required matplotlib version to 3.5.0

setup.cfg, src/cabinetry/__init__.py
Updating to version `0.5.1`. This fixes the lower bound for the `matplotlib` dependency and adopts a better sorting for nuisance parameter ranking.
```
* updating version to 0.5.1
```
=> chore: updating version to 0.5.1

src/cabinetry/visualize/plot_result.py
Minor refactor: the x-axis tick labels can be rotated and aligned directly when set instead of requiring a loop.
```
* rotate and align x-axis tick labels without requiring a loop for correlation matrix visualization
```
=> refactor: correlation matrix tick label rotation and alignment

setup.py
`flake8-import-order` is incompatible with `flake8` version `6.0.0` at the moment, see #379. Temporarily pin to avoid issues and then remove pin once everything is compatible again.
```
* temporarily pin flake8<6 due to incompatibility with flake8-import-order
```
=> build: temporarily pin flake8<6

.pre-commit-config.yaml, src/cabinetry/fit/__init__.py, src/cabinetry/model_utils.py, tests/conftest.py, tests/fit/test_fit.py, tests/test_model_utils.py
The evaluation of the constraint term in the saturated likelihood for goodness-of-fit testing previously used the suggested parameter values for a given model. Those maximize the constraint term only if the auxiliary data used in the fit for which the GOF is being evaluated corresponds to the default `model.config.auxdata`.
This fixes the construction of the parameter values used in the constraint term evaluation to ensure the saturated likelihood is correctly evaluated. Parameter values can be picked up from auxiliary data if they correspond to modifiers with associated constraints, with scaling required for Poisson terms. Other parameter values (corresponding to free-floating parameters) can be picked up from `model.config.suggested_init()`, but do not matter for the constraint term …
=> fix: saturated likelihood evaluation with custom auxiliary data

.pre-commit-config.yaml, src/cabinetry/cli/__init__.py, src/cabinetry/model_utils.py, src/cabinetry/templates/builder.py, src/cabinetry/visualize/__init__.py, tests/conftest.py, tests/test_configuration.py, tests/test_model_utils.py, tests/visualize/test_visualize.py
Applying `black`'s 2023 style via its [23.1a1](https://github.com/psf/black/releases/tag/23.1a1) release. The changes are compatible with prior versions of `black`, so this should not be causing issues in CI. Also running `--skip-magic-trailing-comma` once to adjust cases where expressions may previously have been longer but now can be collapsed back into one line.
```
* apply Black's 2023 style
```
=> style: apply Black's 2023 style

setup.cfg, setup.py
Resolves #379: the pin `flake8<6` introduced temporarily in #380 can be removed, given that a compatible `flake8-import-order` version now exists.
```
* remove temporary flake8 pin
* fix formatting issue with flake8 extend-ignore setting
```
=> build: revert flake8 pin

.pre-commit-config.yaml, src/cabinetry/__init__.py
This fixes code autocompletion for vscode (IntelliSense) by importing the `cabinetry` components differently in the top-level `__init__.py`. Previously they were accessible only via `cabinetry.cabinetry`. `histo` was previously  missing here and is also added, and an appropriate top-level `__all__` is also defined.
```
* fixed editor autocompletion by appropriately importing cabinetry components
* added top-level __all__
```
=> chore: fix editor autocompletion

.pre-commit-config.yaml, setup.py
`typeguard` version 3.0 introduced CI failures in the nightly tests, see #391. Temporarily pin `typeguard<3` to keep using the older version in CI. Eventually the newer version should be adopted in order to take advantage of the additional issues it can catch.
```
* temporarily pin typeguard<3 to fix CI
```
=> fix: temporarily pin typeguard<3

tests/test_cabinetry.py
#386 added `__all__` and `dir()` for `cabinetry`, but did not include a test and coverage for that, which is added by this PR.
```
* test and cover dir(cabinetry)
```
=> test: add test for builtin dir()

.pre-commit-config.yaml, src/cabinetry/cli/__init__.py, tests/cli/test_cli.py
Adds yield tables to the CLI. Output folder and format are configurable.
```
* added yield tables to the command line interface
```
=> feat: command line interface for yield tables

src/cabinetry/model_utils.py, tests/conftest.py, tests/test_model_utils.py
In the presence of partially fixed parameters (currently this only happens for `staterror` modifiers that are constant in some bins due to zero yield + uncertainty, see https://github.com/scikit-hep/pyhf/issues/1944) the previously used `model.config.suggested_fixed_as_bool` will not work. Instead, `model.config.suggested_fixed` works fine to handle these mixed cases.
The same update is made for the counting of the number of unconstrained parameters. This should in principle correctly handle partially fixed `shapefactor` modifiers, however this currently cannot be achieved in `pyhf` (see https://github.com/scikit-hep/pyhf/issues/2053). This means the behavior currently cannot be tested.
resolves #390
```
* fix pre-fit parameter uncertainty evaluation for partially fixed parameters
* …
```
=> fix: parameter uncertainties for partially fixed parameters

src/cabinetry/visualize/plot_model.py, tests/visualize/test_visualize_plot_model.py
related to issue https://github.com/scikit-hep/cabinetry/issues/388.
Tried `python -m pytest`, did not pass all tests even before modifying anything. No additional errors though after the fix and tested with samples mantioned in issue https://github.com/scikit-hep/cabinetry/issues/388.
=> fix: handle negative model predictions in visualizations

setup.cfg, src/cabinetry/__init__.py
Updating to version `0.5.2`. This fixes the handling of parameter uncertainties for partially fixed parameters and the handling of negative model predictions in plots, adds yield tables to the command line interface, and improves editor autocompletion.
```
* updating version to 0.5.2
```
=> chore: updating version to 0.5.2

src/cabinetry/workspace.py, tests/test_workspace.py
There is no need to create `histosys` modifiers for single-bin regions, as the full effect is already absorbed into the `normsys` modifier created in that case.
```
* skip superfluous histosys modifier creation for single-bin regions
```
resolves #354
=> feat: skip histosys modifier creation for single-bin regions

src/cabinetry/visualize/__init__.py, src/cabinetry/visualize/plot_model.py, tests/visualize/test_visualize.py, tests/visualize/test_visualize_plot_model.py
Adding a new `colors` argument to `visualize.data_mc` and `visualize.data_mc_from_histograms` (as well as `visualize.plot_model.data_mc`) that allows specifying color names per sample: `colors={"signal": "red", "background": "blue"}`. Colors need to be provided for all samples, otherwise an exception is raised. If colors are invalid, an exception will later on be raised via `matplotlib`. The default behavior is unchanged, falling back to the `seaborn-colorblind` colors.
`visualize.data_mc_from_histograms` was still missing the `channels` kwarg, this is now also included. 
```
* support custom histogram colors for visualize.data_mc via new colors keyword argument
* support custom histogram colors in visualize.plot_model.data_mc
* extend color and channel filtering functionality to …
```
=> feat: support custom colors for data/MC plots

.github/workflows/CI.yml, .github/workflows/dependencies-head.yml, .github/workflows/test-package.yml, .pre-commit-config.yaml, setup.cfg
Given https://github.com/scikit-hep/pyhf/pull/2145 and discussion in https://github.com/conda-forge/cabinetry-feedstock/pull/3 add Python 3.11 to testing for `cabinetry`.
* Add Python 3.11 to testing in CI.
* Default to using Python 3.11 in GitHub Actions where possible.
* Update to using Python 3.11 in mypy pre-commit hook.
* Add Python 3.11 trove classifier to PyPI metadata.
=> feat: add Python 3.11 support

src/cabinetry/cli/__init__.py
`click` opens files for writing lazily, meaning that a file opened for writing is not immediately an `io.TextIOWrapper` but a `click.utils.LazyFile` for the purpose of typing: https://click.palletsprojects.com/en/8.1.x/api/#click.File. This was flagged by `typeguard` version `4.0.0rc4` (which will be adopted after full release via #391).
```
* fix typing for file opened for writing with click in command line interface
```
=> fix: typing for file opened for writing with click

.github/workflows/CI.yml, .pre-commit-config.yaml, pyproject.toml, setup.cfg, setup.py, src/cabinetry/_typing.py, src/cabinetry/configuration.py, src/cabinetry/fit/__init__.py, src/cabinetry/histo.py, src/cabinetry/route.py, src/cabinetry/templates/builder.py, src/cabinetry/templates/collector.py, src/cabinetry/templates/postprocessor.py, src/cabinetry/templates/utils.py, src/cabinetry/visualize/plot_model.py, src/cabinetry/visualize/plot_result.py
Following `pyhf` (https://github.com/scikit-hep/pyhf/pull/2044), this drops support for Python 3.7. The NEP 29 schedule puts Python 3.8+ at Dec 26, 2021, which already was one and a half years ago. The last `cabinetry` version to support Python 3.7 will presumably remain `0.5.2` (alongside with `pyhf` version `0.7.1`).
This allows dropping the `_typing` submodule that was used for the `Literal` type via `typing_extensions` with Python 3.7.
Ran `pyupgrade --py38-plus`, which did not seem to introduce any other changes.
The previous drop of Python 3.6 happened in #194. These changes also mean that `pre-commit` `mypy` is again testing against the lowest supported version (see #371).
```
* future versions of cabinetry require at least Python 3.8
* drop support and testing of Python 3.7
* …
```
=> build: drop support for Python 3.7

src/cabinetry/fit/__init__.py, tests/fit/test_fit.py
Add a `(constant)` flag when printing parameters that were held fixed in fits, which subsequently have zero uncertainty. This allows for more easily distinguishing them from the rest.
```
* denote constant parameters as such when printing fit results
```
=> feat: denote constant parameters when printing fit results

src/cabinetry/visualize/__init__.py
Small fix for consistency: `np.ndarray` is the correct return value type of `visualize._total_yield_uncertainty` instead of `np.array`. The type hint was already correct.
```
* fix return value type in docstring of visualize._total_yield_uncertainty
```
=> docs: fix return value type in docstring

.pre-commit-config.yaml, pyproject.toml
The latest version of `numpy`, 1.25.0, dropped compatibility with Python 3.8. When using `mypy` on `cabinetry` with Python 3.8 and the settings from the `pyproject.toml`, this results in errors getting raised in `cabinetry`. An example is the following:
```python
import numpy as np
a = np.asarray([1, 2, 3])
b = a.copy()
c = a.copy().astype(float)
d: np.ndarray = a.copy().astype(float)
```
resulting in
```python
test.py:5: error: Need type annotation for "c"  [var-annotated]
c = a.copy().astype(float)
^~~~~~~~~~~~~~~~~~~~~~
Found 1 error in 1 file (checked 1 source file)
```
This is addressed here by raising the minimum Python version for the type checks being performed to Python 3.9.
```
* raise minimum Python version for mypy to Python 3.9 for compatibility with numpy 1.25.0
```
=> fix: raise minimum Python version for type checking to 3.9

src/cabinetry/model_utils.py
`ak.sum` is much more expensive than anticipated, so this changes the matrix operations in `yield_stdev` to use `numpy` instead, as per suggestion by @alexander-held
partially addresses #409, follows initial improvements done in #315
=> perf: drop use of awkward in yield uncertainty calculation

.github/workflows/dependencies-head.yml, pyproject.toml, setup.cfg, src/cabinetry/tabulate.py
Following #408 there was only one place left where `awkward` was used in the `cabinetry` code base, in `cabinetry.tabulate`. The use of awkward there was not crucial, so this is replaced by pure `numpy` here. This means that the explicit `awkward` dependency can be dropped from `cabinetry`. It still enters in `cabinetry[contrib]` via `uproot`.
```
* drop explicit dependency on awkward
* remove awkward HEAD tests from nightly CI tests
```
=> build: drop explicit awkward dependency

src/cabinetry/model_utils.py
Following #409, a close look through `model_utils` revealed that the description of the model prediction indices needed a few improvements, which is done here.
```
* improve description of the indices of yield predictions and uncertainties
```
=> docs: improve yield prediction index descriptions

src/cabinetry/visualize/__init__.py, tests/visualize/test_visualize.py
The presence of spaces in region / sample / systematic names previously caused the corresponding templates to not get picked up via `visualize.templates`, which is now fixed.
```
* fix visualize.templates not correctly handling template histograms with spaces in names
```
=> fix: handling spaces in histogram names for template visualization

setup.py
Context in #428: the latest `typeguard` releases (`>=4.0.1`) require `typing_extension>=4.7.0`, which are versions beyond the cap put on it by Tensorflow. The next Tensorflow release removes that cap. In the meantime, restrict the specific `typeguard` versions that cause the clash. This will be reverted after the Tensorflow release.
```
* temporarily restrict typeguard versions to avoid dependency clash via typing_extensions due to Tensorflow
```
=> build: temporarily restrict latest typeguard to avoid dependency clash

setup.py, src/cabinetry/histo.py, tests/test_histo.py
The `WARNING` log level when histogram post-processing is not called seemed a bit too high. This is now an `INFO` level message instead.
Extending the `typeguard` version restrictions to handle #428.
resolves #432
```
* lower warning-level messages when histogram post-processing is not used to info-level messages
* temporarily restrict more typeguard versions to avoid typing_extensions conflict due to TensorFlow
```
=> feat: turn warnings about missing post-processed histograms into info messages

docs/core.rst, src/cabinetry/contrib/histogram_creator.py, src/cabinetry/contrib/histogram_reader.py, src/cabinetry/templates/builder.py, src/cabinetry/templates/collector.py, tests/templates/test_templates_collector.py
As discussed in #435 and originally via #433, `SamplePath` overrides are needed to provide additional flexibility for histogram inputs. This adds support for such overrides. For easier debugging, a new `DEBUG` level message is also added to report the location of histogram and ntuple inputs.
```
* support SamplePath overrides when using histogram inputs
* update documentation for histogram inputs
* add debug-level log message with paths to ntuple and histogram inputs
```
=> feat: support SamplePath overrides for histogram inputs

setup.cfg, src/cabinetry/__init__.py
Updating to version `0.6.0`, which brings Python 3.11 support and drops Python 3.7. It also adds support for custom colors in data/MC plots, more flexibility for histogram input paths, speeds up post-fit yield uncertainty calculations and includes a few bug fixes.
```
* updating version to 0.6.0
```
=> chore: updating version to 0.6.0

README.md, docs/index.rst
Adding award number [PHY-2323298](https://www.nsf.gov/awardsearch/showAward?AWD_ID=2323298) to both readme and documentation.
```
* add award number for second phase of IRIS-HEP to readme and documentation
```
=> docs: add award number for second phase of IRIS-HEP

.github/workflows/CI.yml, setup.py
To avoid a `typing_extension` clash caused by TensorFlow, #429 restricted the `typeguard` version listed in the `test` setup extra. Now that an updated TensorFlow version is available, which fixes this clash, the `typeguard` version restriction can be relaxed again.
The `typing-extensions` cap introduced in `tensorflow-probability` has been fixed, but the versions with the fix are Python 3.9+ and therefore cause issues in the CI for 3.8. To avoid this, upgrade the `typing_extensions` version in the relevant Python 3.8 CI.
resolves #428
```
* relax version constraint on typeguard as latest TensorFlow release no longer causes dependency clash
* upgrade typing-extensions version in Python 3.8 CI to circumvent dependency clash
```
=> build: relax typeguard constraints following TensorFlow release

.github/workflows/CI.yml, .github/workflows/dependencies-head.yml, .github/workflows/test-package.yml
Update actions versions of `checkout`, `setup-python` and `codecov`. Temporarily skip `black` in CI, to be fixed via #458 afterwards.
```
* update GitHub actions versions of checkout, setup-python and codecov
* enable verbose output for codecov action
* temporarily skip black in CI
```
=> ci: update GitHub actions versions

.github/workflows/CI.yml, .pre-commit-config.yaml, src/cabinetry/cli/__init__.py, tests/conftest.py, tests/test_workspace.py, tests/visualize/test_visualize_plot_model.py, utils/create_histograms.py, utils/create_ntuples.py
Applying latest `black` formatting corresponding to the stable 2024 style with tag [24.1.0](https://github.com/psf/black/releases/tag/24.1.0). Running also once with `--skip-magic-trailing-comma` to adjust leftover commas. See also #383 for the previous version of this PR. Also adding `black` back to CI following the temporary removal in #459.
```
* apply Black's 2024 style
* add back black to CI
```
=> style: apply Black's 2024 style

.pre-commit-config.yaml, src/cabinetry/visualize/plot_result.py
As flagged by #463, the impact axis range did not correctly take into account cases where the largest impacts were post-fit. This can happen in particular for normalization factors, which have no pre-fit impact defined.
```
* take into account both pre- and post-fit impacts when setting ranking plot axis range
```
=> fix: ranking plot axis range for normalization factors

tests/test_backends.py
Due to `tensorflow` / `tensorflow-probability` diverging, the TensorFlow backend as installed from `pyhf[backends]` is currently broken in the latest released `pyhf` version (`v0.7.6`) and fixed in `main` via https://github.com/scikit-hep/pyhf/pull/2452. Temporarily skip this backends in tests until the next released version of `pyhf`.
```
* temporarily skip TensorFlow backend in tests
```
=> test: temporarily skip TensorFlow in tests

.pre-commit-config.yaml, src/cabinetry/workspace.py, tests/test_workspace.py
Template symmetrization was previously only possible for up variations (meaning the down variation is created via symmetrization). This update also enables symmetrization for down variations.
```
* allow symmetrization of down variations to create templates for up variations
```
=> feat: allow symmetrization of down variations

src/cabinetry/fit/__init__.py
A bug fix in `typeguard` [4.2.0](https://github.com/agronholm/typeguard/releases/tag/4.2.0) started flagging a type inconsistency where `model.config.suggested_bounds()` contains elements that are lists instead of tuples with custom parameter bound configuration, see https://github.com/scikit-hep/pyhf/issues/2462. This fix here works around this by explicitly converting to a list of tuples for further use within `cabinetry`.
If the behavior in `pyhf` changes, this should be reverted / adjusted in the future.
```
* convert parameter bounds to list of tuples for consistent types when custom bounds are used
```
=> fix: explicitly convert parameter bounds to list of tuples

.github/workflows/CI.yml, .github/workflows/dependencies-head.yml, .github/workflows/test-package.yml, .pre-commit-config.yaml, .readthedocs.yaml, setup.cfg
Resolves #446 
```
* docs: Add Python 3.12 PyPI trove classifier
* ci: Add Python 3.12 to CI
* ci: Add workflow dispatch trigger to CI
* ci: List installed Python packages
```
=> feat: add Python 3.12 support

.pre-commit-config.yaml, src/cabinetry/histo.py
The histogram validation prints indices slightly differently in `numpy` 2.0 (`[np.int64(1)]`), which caused a test to fail. This is fixed here.
```
* fix the way histogram indices are represented for numpy 2.0
```
=> fix: histogram validation test for numpy 2.0

src/cabinetry/schemas/config.json, tests/test_configuration.py
The config schema has previously been very restrictive, not allowing unknown top-level properties. The intention was to help catch possible spelling mistakes, but at the top level this seems less likely and restricts the config when users may want to add custom information to the same file. To facilitate such use cases, allow for custom keys at the top level.
```
* allow custom top-level properties in configuration schema
```
=> feat: allow custom top-level properties in configuration schema

.pre-commit-config.yaml, src/cabinetry/tabulate.py, tests/test_tabulate.py
Applying latest `black` formatting corresponding to the stable 2025 style with tag [25.1.0](https://github.com/psf/black/releases/tag/25.1.0). This only affects unicode escape characters this time. The 2024 iteration of this was #458. Also temporarily disabling `mypy`, to be fixed in follow-up PR.
```
* apply Black's 2025 style
* temporarily skip mypy in pre-commit tests
```
=> style: apply Black's 2025 style

src/cabinetry/fit/__init__.py, tests/fit/test_fit.py
Extend the `cabinetry.fit.fit` interface to set custom confidence levels. The interface follows `iminuit`'s [`minos`](https://scikit-hep.org/iminuit/reference.html#iminuit.Minuit.minos) API in terms of functionality but uses a `minos_cl` argument name instead.
```
* added customizable confidence level for MINOS to fit.fit
```
=> feat: customizable confidence level for MINOS

src/cabinetry/visualize/plot_model.py
#496 added functionality to truncate long label names, but the prediction label (e.g. "pre-fit") was part of the same string and also got truncated. This fixes the behavior to truncate per line.
```
* truncate channel name and prediction label per line on data/MC plots
```
=> fix: truncate labels on data/MC plots per line

src/cabinetry/fit/__init__.py, tests/fit/test_fit.py
The old error message did not make it explicit which numbers were POI values, the new version should be a bit more clear.
```
* add POI name to error message to better distinguish between POI and CLs values
```
=> feat: improve error message when CLs bracketing fails

CITATION.cff, README.md
Resolves #492 
* Add CITATION.cff for the software and the vCHEP paper.
* Update vCHEP paper to use published DOI.
- c.f. https://doi.org/10.1051/epjconf/202125103067
```console
$ pixi global install cffconvert
$ cffconvert --validate --infile CITATION.cff
Citation metadata are valid according to schema version 1.2.0.
```
=> docs: Add CITATION.cff file and update vCHEP DOI

tests/test_integration.py, utils/create_ntuples.py
Adresses #507.
```
* Allow `create_ntuples` util script to accept output directory from CLI.
```
=> feat: allow create_ntuples utility to accept an output directory from a CLI

src/cabinetry/fit/__init__.py, src/cabinetry/model_utils.py, tests/fit/test_fit.py, tests/test_model_utils.py
Solves #478 by passing fixed parameters to `model_utils.unconstrained_parameter_count`.
=> fix: respect fixed parameters in n_dof calculation

.pre-commit-config.yaml, src/cabinetry/fit/__init__.py, src/cabinetry/model_utils.py, src/cabinetry/workspace.py
#498 temporarily removed `mypy` from pre-commit, this adds it back. The changes required are related to typing changes in `numpy` v2.2.
The incompatible types problem in the `.tolist()` context seem to originate from a bug in `mypy` as discussed in https://github.com/numpy/numpy/issues/27944. `numpy` recommends [`basedpyright`](https://github.com/DetachHead/basedpyright) in the [2.2.1 release notes](https://github.com/numpy/numpy/releases/tag/v2.2.1), a potential consideration for the future.
```
* enable mypy in pre-commit tests again
* manually type cast to avoid mypy bugs with .tolist() calls in numpy
```
=> fix: type checking fixes for numpy 2.2 and add mypy back to pre-commit

tests/fit/test_fit.py
This very slightly extends #479 to test that custom fixed parameter settings correctly propagate.
```
* test propagation of fixed parameter settings for goodness-of-fit degree of freedom counting
```
=> test: custom fixed parameter settings for goodness-of-fit

.github/workflows/CI.yml
In #515  the coverage was observed to be underestimated due to the use of `xfail()` to handle the issue described in #476. This reduced coverage was not observed locally (with `python 3.9.7`). It happens because the CI still uses `python 3.8` to report coverage. This python version will be eventually deprecated, and it makes sense to not use it for code coverage anymore. 
```
* bump python version used to generate code coverage to 3.8
* Run tests for python > 3.9 and python 3.8 separately with no coverage
```
=> chore: bump python version used for codecov in CI

.github/workflows/blocking_issues.yml
This can help with organisation, to automatically detect if a PR should not be merged until another is merged,  or until some issue is resolved. 
Using the following action: https://github.com/Levi-Lesches/blocking-issues
```
* add a GitHub action to test for PR/issue blockers and report them in the PRs/issues
```
=> ci: Add a GitHub action to handle issue/PR blockers 

.pre-commit-config.yaml, src/cabinetry/histo.py
Version [2.3.0](https://github.com/numpy/numpy/releases/tag/v2.3.0) of `numpy` brought some typing changes that require small adjustments to some type ignores we have in place (some more context about them is in #204 and https://github.com/scikit-hep/boost-histogram/issues/527). This update allows pre-commit CI to pass `mypy` again.
```
* type ignores updated for compatibility with numpy 2.3.0
```
=> fix: type ignores for numpy 2.3

src/cabinetry/model_utils.py, tests/conftest.py, tests/test_backends.py, tests/test_model_utils.py
A new `sample_update_map` argument to `model_utils.yield_stdev` and `model_utils.prediction` allows merging or renaming samples for presentation in yield tables or data/MC visualizations. Example:
```python
sample_update_map = {"Total Background": ["Background", "Background 2"]}
```
All samples that are not included in the map stay unchanged.
resolves #502
```
* add new sample_update_map argument to model_utils.yield_stdev and model_utils.prediction
* sample_update_map allows merging samples for yield tables and data/MC visualizations
* create lightweight version of pyhf model configuration to propagate information within cabinetry
* allow using LightModel and pyhf model interchangeably where possible within model_utils module
```
=> feat: allow merging of samples for displaying model predictions

tests/test_backends.py
A former `DeprecationWarning` when using the `pytorch` backend in `pyhf` has now turned into a `TypeError`. Temporarily skip this backends in tests until fixed upstream, tracked via https://github.com/scikit-hep/pyhf/issues/2554. This is similar to #468 disabling TensorFlow.
```
* temporarily skip pytorch backend in tests
```
=> test: temporarily skip pytorch in tests
