scikit-hep/cabinetry

.github/workflows/CI.yml, example.py, util/create_histograms.py
This PR just goes full Black mode on everything, by changing the lint check in CI to run on all files in the repo and then likewise applying that same criteria to the repo itself. If there is motivation to only Black the codebase and not the whole repo this PR should be closed.
```
* Apply Black to all files in the repo
* Lint all files with Black
```
=> chore: Black everything

.gitignore, config_example.yml, example.py, setup.py, src/cabinetry/__init__.py, src/cabinetry/config.py, src/cabinetry/contrib/histogram_drawing.py, src/cabinetry/histo.py, src/cabinetry/workspace.py
Adding the possibility to build HistFactory workspaces in [pyhf](https://github.com/scikit-hep/pyhf/) style.
Also clearing matplotlib figure after drawing to fix drawing for multiple regions.
=> feat: workspace building

example.py, src/cabinetry/__init__.py, src/cabinetry/fit.py
Adding support for simple unconstrained maximum likelihood fits through `pyhf`.
=> feat: basic unconstrained fitting

README.md, config_example.yml, src/cabinetry/workspace.py
Adding `OverallSys` (in `HistFactory` language) / `normsys` (in `pyhf` language) support. This prompted some more thoughts on configuration file design, which are added to the readme.
=> feat: normalization systematic support

src/cabinetry/config.py, src/cabinetry/fit.py, src/cabinetry/histo.py, src/cabinetry/template_builder.py, src/cabinetry/template_postprocessor.py, src/cabinetry/visualize.py, src/cabinetry/workspace.py
Updating docstrings for fit/workspace modules, plus some changes for consistency.
=> docs: docstring updates

README.md
adding a link to the relevant readme section
=> docs: link to issue about file paths

.github/workflows/CI.yml, .gitignore
adding coverage reports to CI, using https://codecov.io/
=> ci: coverage reports

setup.py, src/cabinetry/__init__.py
updating package version for next tag
=> chore: updating version

src/cabinetry/configuration.py, src/cabinetry/contrib/histogram_drawing.py, src/cabinetry/template_builder.py, tests/test_configuration.py
fixing some stylistic issues flagged by https://www.codefactor.io/
=> style: issues flagged by codefactor 

src/cabinetry/template_builder.py, tests/contrib/test_histogram_creation.py, tests/test_template_builder.py, tests/utils.py
adding another test for template histogram creation
=> test: template generation

src/cabinetry/configuration.py, src/cabinetry/template_builder.py, src/cabinetry/visualize.py, tests/conftest.py, tests/contrib/test_histogram_creation.py, tests/contrib/test_histogram_drawing.py, tests/test_configuration.py, tests/test_fit.py, tests/test_histo.py, tests/test_template_builder.py, tests/test_template_postprocessor.py, tests/test_visualize.py, tests/test_workspace.py, tests/utils.py
- moving test utilities to `conftest.py` to provide them as fixtures
- parametrizing test with fixtures
- adding more error messages where they are missing
- more careful testing of errors with type and message
=> test: refactor tests

README.md
adding coverage badge to readme, and moving config file discussion to #43
=> docs: coverage and config file

setup.py, src/cabinetry/__init__.py
updating version for next tag and pypi release
=> chore: updating version to 0.0.4

README.md, docs/index.rst
Updating the hello world example in the readme and removing it from the sphinx docs. Also implementing a few small text updates in the readme.
=> docs: update hello world example

src/cabinetry/workspace.py, tests/test_visualize.py, tests/test_workspace.py
Replacing an assertion in the library by an error, and adding a small refactor to a test.
=> refactor: two minor updates

setup.py, src/cabinetry/__init__.py
Updating patch version to release 0.1.1 with the fix for observed data from #90.
=> chore: updating version to 0.1.1

.github/workflows/CI.yml, docs/index.rst
Adding sphinx docs building to the CI to catch potential issues before merging.
=> ci: adding sphinx docs building

setup.cfg, src/cabinetry/__init__.py
Updating to 0.1.4. Includes bugfix from #129 to allow data/MC visualization of three and more channels.
=> chore: updating version to 0.1.4

setup.cfg, src/cabinetry/__init__.py
Updating to 0.1.5. Includes the update from #135 for compatibility with `pyhf` 0.5.3.
=> chore: updating version to 0.1.5

CONTRIBUTING.md
Adding contribution guidelines.
=> docs: contribution guidelines

src/cabinetry/fit.py, tests/test_fit.py
This minor change moves `fit. _run_minos` to a better location in the file it is defined in, to be grouped together with similar functions instead of public API functions.
=> style: move MINOS function to better position

setup.cfg, src/cabinetry/__init__.py
Updating to 0.1.6 to resolve #161.
=> chore: updating version to 0.1.6

src/cabinetry/fit.py
The cache introduced in #172 can be used to access some values for calculations inside `fit.limit` that were previously also stored as lists (POI values, observed/expected CLs values). This removes the lists and uses the cache instead.
=> refactor: remove superfluous lists in limit calculation

setup.cfg, src/cabinetry/__init__.py
Updating to 0.1.8, introducing systematic template smoothing, more efficient limit finding, and horizontal log scale for data/MC plots.
=> chore: updating version to 0.1.8
